// app/(marketing)/answers/cross-link.ts
// Topical slug -> /answers slug mappings used to cross-link /generators and
// /best pages to genuinely related /answers pages. Only pages with a real
// topical match get an entry — most /generators and /best slugs (Twitter,
// Instagram, sales-team, scheduling niches with no matching answer topic)
// intentionally have no mapping and render no cross-link.

export const GENERATOR_TO_ANSWER_SLUGS: Record<string, string[]> = {
  "linkedin-carousel-maker": ["linkedin-carousel-dimensions", "how-to-make-a-linkedin-carousel-without-canva"],
  "linkedin-carousel-generator": ["linkedin-carousel-dimensions", "how-many-slides-should-a-carousel-have"],
  "ai-carousel-generator": ["how-to-make-a-linkedin-carousel-without-canva", "can-ai-generate-linkedin-images"],
  "carousel-post-maker": ["linkedin-carousel-dimensions", "how-long-should-a-linkedin-carousel-be"],
  "linkedin-carousel-template": ["how-many-slides-should-a-carousel-have", "best-linkedin-carousel-aspect-ratio"],
  "topic-to-carousel-generator": ["how-to-make-a-linkedin-carousel-without-canva"],
  "text-to-carousel-generator": ["linkedin-carousel-character-limit-per-slide"],
  "pdf-to-linkedin-carousel": ["linkedin-carousel-pdf-requirements"],
  "ai-caption-generator": ["how-to-write-a-linkedin-caption", "can-ai-write-good-linkedin-content"],
  "linkedin-caption-generator": ["how-to-write-a-linkedin-caption", "best-linkedin-caption-structure"],
  "linkedin-post-generator": ["how-to-write-a-linkedin-hook", "best-linkedin-post-length-for-engagement"],
  "ai-post-generator": ["can-ai-write-good-linkedin-content"],
  "linkedin-hook-generator": ["how-to-write-a-linkedin-hook", "best-linkedin-hook-formulas"],
  "linkedin-text-post-generator": ["how-long-should-a-linkedin-post-be"],
  "ai-image-generator-for-linkedin": ["can-ai-generate-linkedin-images", "how-to-make-a-linkedin-post-image"],
  "linkedin-post-image-generator": ["best-image-size-for-linkedin-post", "linkedin-single-image-dimensions"],
  "linkedin-infographic-generator": ["linkedin-infographic-size-guide"],
  "linkedin-post-ideas-generator": ["linkedin-post-ideas-for-beginners", "what-to-post-when-you-have-nothing-to-say"],
  "ai-content-idea-generator": ["what-to-post-when-you-have-nothing-to-say", "content-pillars-for-linkedin"],
  "content-calendar-generator": ["linkedin-content-calendar-how-to-build-one", "how-to-batch-create-linkedin-content"],
  "linkedin-content-generator": ["content-pillars-for-linkedin"],
  "ai-social-media-content-generator": ["can-ai-write-good-linkedin-content"],
  "free-linkedin-post-generator": ["how-to-write-a-linkedin-hook"],
  "free-ai-caption-generator": ["how-to-write-a-linkedin-caption"],
  "free-linkedin-carousel-maker": ["how-to-make-a-linkedin-carousel-without-canva"],
  "ai-content-creation-tool-for-linkedin": ["can-ai-write-good-linkedin-content", "best-ai-tool-for-linkedin-content"],
  "linkedin-personal-branding-tool": ["how-to-build-a-personal-brand-on-linkedin"],
  "linkedin-carousel-size-guide": ["linkedin-carousel-dimensions"],
  "quote-card-generator": ["best-image-size-for-linkedin-post"],
  "carousel-slide-generator": ["how-many-slides-should-a-carousel-have"],
  "multi-slide-post-generator": ["how-long-should-a-linkedin-carousel-be"],
}

export const BEST_TO_ANSWER_SLUGS: Record<string, string[]> = {
  "best-ai-caption-generators": ["how-to-write-a-linkedin-caption"],
  "best-ai-carousel-generators-compared": ["linkedin-carousel-dimensions", "how-to-make-a-linkedin-carousel-without-canva"],
  "best-ai-content-creation-tools-for-linkedin": ["can-ai-write-good-linkedin-content", "best-ai-tool-for-linkedin-content"],
  "best-ai-image-generators-for-social-media": ["can-ai-generate-linkedin-images"],
  "best-ai-tools-for-b2b-content-marketing": ["linkedin-content-ideas-for-b2b"],
  "best-ai-tools-for-content-repurposing": ["how-to-repurpose-a-blog-post-for-linkedin", "how-to-repurpose-one-idea-into-a-week-of-posts"],
  "best-ai-tools-for-linkedin-carousels": ["linkedin-carousel-dimensions", "how-to-make-a-linkedin-carousel-without-canva"],
  "best-ai-tools-for-personal-branding-on-linkedin": ["how-to-build-a-personal-brand-on-linkedin"],
  "best-ai-tools-for-startup-founders-on-linkedin": ["what-to-post-on-linkedin-as-a-founder"],
  "best-ai-tools-for-thought-leadership-content": ["how-to-become-a-linkedin-thought-leader"],
  "best-ai-writing-tools-for-social-media": ["can-ai-write-good-linkedin-content"],
  "best-carousel-makers-for-founders": ["what-to-post-on-linkedin-as-a-founder", "how-to-make-a-linkedin-carousel-without-canva"],
  "best-carousel-tools-with-brand-kit": ["linkedin-carousel-dimensions"],
  "best-free-linkedin-carousel-tools": ["how-to-make-a-linkedin-carousel-without-canva"],
  "best-linkedin-carousel-generators": ["how-to-make-a-linkedin-carousel-without-canva", "how-many-slides-should-a-carousel-have"],
  "best-linkedin-carousel-generators-for-agencies": ["how-to-batch-create-linkedin-content"],
  "best-linkedin-carousel-generators-for-solopreneurs": ["how-to-make-a-linkedin-carousel-without-canva"],
  "best-linkedin-content-tools-2026": ["best-ai-tool-for-linkedin-content"],
  "best-linkedin-content-tools-for-agencies": ["how-to-batch-create-linkedin-content"],
  "best-linkedin-post-generators": ["how-to-write-a-linkedin-hook"],
  "best-linkedin-scheduling-and-content-tools": ["linkedin-content-calendar-how-to-build-one"],
  "best-linkedin-tools-for-coaches": ["what-to-post-on-linkedin-as-a-coach"],
  "best-linkedin-tools-for-consultants": ["linkedin-content-ideas-for-consultants"],
  "best-social-media-carousel-tools": ["linkedin-carousel-dimensions"],
  "best-tools-for-linkedin-personal-branding": ["how-to-build-a-personal-brand-on-linkedin"],
  "best-tools-to-turn-blog-posts-into-carousels": ["how-to-repurpose-a-blog-post-for-linkedin"],
}
