// app/(marketing)/answers/content/carousels.ts
// Carousels answer pages for the /answers/[slug] programmatic SEO system.

import type { AnswerPage } from "../types"

export const carouselsAnswers: AnswerPage[] = [
  {
    slug: "linkedin-carousel-dimensions",
    question: "What are the correct dimensions for a LinkedIn carousel?",
    metaTitle: "LinkedIn Carousel Dimensions: The Exact Sizes to Use",
    metaDescription: "The correct LinkedIn carousel dimensions are 1080×1080px (square) or 1080×1350px (portrait), exported as PDF. See which size to use and why.",
    directAnswer: "LinkedIn carousels should be built at 1080×1080px (square) or 1080×1350px (4:5 portrait) per slide, exported as a single PDF and uploaded through the \"Add a document\" option. Square is the safer default for readability across devices, while portrait uses more vertical feed space on mobile, where most LinkedIn traffic happens.",
    explanation: "LinkedIn doesn't publish an official carousel dimension spec — carousels are technically PDF documents uploaded through the post composer, not a dedicated carousel feature — so the sizing convention comes from what consistently displays cleanly inside the feed's document viewer without cropping, awkward margins, or LinkedIn compressing the file into blurriness.\n\n1080×1080px (square) is the safer default because it displays fully in both the desktop and mobile feed without the top or bottom getting clipped by the viewer's preview window. 1080×1350px (4:5 portrait) takes up more vertical screen space on mobile, which can increase dwell time since it's harder to scroll past — but it's more prone to minor cropping in some feed previews, so test it before committing an entire content calendar to portrait.\n\nWhichever ratio you choose, keep it consistent across every slide in a single carousel — mixing square and portrait slides in one document creates jarring size jumps as readers swipe through. Export everything as one combined PDF, not individual image files, since LinkedIn's carousel format only accepts document uploads. CarouseLabs applies the correct dimensions and exports a ready-to-upload PDF automatically, so you don't have to set canvas sizes by hand in a design tool.\n\nLeave a safe margin inside every slide, regardless of which ratio you pick. LinkedIn's document viewer sometimes shows a thin surrounding frame or slightly different crop across desktop, mobile, and shared-link previews, so text or logos placed flush against the edge can end up clipped in at least one of those views. Keeping key content roughly 60-80px inside the border on all sides avoids that problem without noticeably shrinking the usable slide area.",
    keyPoints: [
      "1080×1080px (square) is the safest default for full display across devices",
      "1080×1350px (4:5 portrait) uses more mobile screen space, but test it before committing fully",
      "Keep every slide in a carousel the same dimensions — never mix ratios within one document",
      "Export as a single combined PDF, not separate image files — LinkedIn's carousel upload only accepts documents",
    ],
    example: "A creator posting a 9-slide \"lessons from my first year of freelancing\" carousel builds every slide at 1080×1080px, combines them into one PDF using consistent margins, and uploads it via \"Add a document\" — rather than uploading 9 separate JPGs, which LinkedIn doesn't support as a swipeable carousel.",
    relatedFaq: [
      { question: "Does LinkedIn compress carousel images?", answer: "Yes, LinkedIn compresses uploaded documents somewhat, but starting at 1080px wide keeps quality well above the compression threshold, so text and graphics stay sharp after upload." },
      { question: "How many slides should a LinkedIn carousel have?", answer: "Most high-performing carousels run 7-9 slides — enough to set up a hook, deliver substance, and close with a takeaway, without losing readers who drop off in longer decks." },
    ],
    category: "Carousels",
    relatedSlugs: ["how-many-slides-should-a-carousel-have", "linkedin-carousel-file-size-limit", "best-linkedin-carousel-aspect-ratio", "linkedin-carousel-pdf-requirements"],
  },
  {
    slug: "how-to-make-a-linkedin-carousel-without-canva",
    question: "How do you make a LinkedIn carousel without Canva?",
    metaTitle: "How to Make a LinkedIn Carousel Without Canva",
    metaDescription: "Make a LinkedIn carousel without Canva using CarouseLabs — describe your topic, pick a structure, and get a designed, ready-to-post carousel in minutes.",
    directAnswer: "You can make a LinkedIn carousel without Canva using CarouseLabs, which generates both the caption and a full multi-slide carousel — with matching fonts, colors, and layout — directly from a topic or idea, skipping manual slide design entirely. Describe what you want to post about, choose a structure, and export ready-to-post slides in minutes.",
    explanation: "Canva works, but it wasn't built for carousels specifically — you're manually duplicating a slide template, retyping text on each one, and eyeballing whether slide 4 still matches the font size and color you used on slide 1. For a single one-off post that's tolerable; for a regular publishing habit, it becomes the slowest part of your week.\n\nCarouseLabs approaches it differently: instead of starting from a blank template, you start from your idea. You type out what you want to post about — a lesson, a framework, a mistake you made — and choose how the carousel should be structured, either from over 30 pre-built slide-flow templates (problem → solution, before → after, myth vs. truth) or by describing your own. From there, the tool writes a caption and designs every slide with consistent typography and layout, pulling from a style reference if you upload one so new carousels match your existing visual brand.\n\nThe practical difference is what you're doing with your time: in Canva you're a layout technician; in CarouseLabs you're reviewing and editing content that's already been designed. For anyone publishing more than one carousel a week, that difference compounds fast.\n\nThe generated draft is also a starting point, not a final answer you're stuck with. If a specific slide's wording feels off or a structure doesn't quite fit the story once you see it laid out, you can revise the text or regenerate that section rather than starting the whole carousel over — which keeps the workflow closer to editing a draft than to rebuilding a design from a blank canvas each time something needs adjusting.",
    keyPoints: [
      "CarouseLabs generates the caption and a full designed carousel from a topic, with no manual slide layout required",
      "Choose from 30+ slide-flow structures, or describe your own and let AI build one",
      "Upload a past post as a style reference to keep new carousels visually consistent with your existing brand",
      "Export a ready-to-upload PDF, or post directly — no separate design step before publishing",
    ],
    example: "A consultant with a client story to share types two sentences about the situation into CarouseLabs, picks the \"before → after\" structure, and gets a complete 8-slide carousel with a written caption in under five minutes — instead of spending 45+ minutes in Canva manually resizing text boxes across each slide.",
    relatedFaq: [
      { question: "Is there a free way to make a LinkedIn carousel without Canva?", answer: "CarouseLabs offers a free tier to try carousel creation without a credit card, so you can test the workflow before committing to a paid plan." },
      { question: "Do I need design skills to use CarouseLabs instead of Canva?", answer: "No — CarouseLabs handles font, color, and layout decisions automatically. You provide the topic and structure; the visual design is generated for you." },
    ],
    category: "Carousels",
    relatedSlugs: ["how-many-slides-should-a-carousel-have", "linkedin-carousel-vs-single-image-which-performs-better", "linkedin-carousel-dimensions", "how-long-should-a-linkedin-carousel-be"],
  },
  {
    slug: "how-many-slides-should-a-carousel-have",
    question: "How many slides should a LinkedIn carousel have?",
    metaTitle: "How Many Slides Should a LinkedIn Carousel Have?",
    metaDescription: "The ideal LinkedIn carousel runs 7-9 slides — enough for a hook, substance, and a close, without losing readers to swipe drop-off. See the full breakdown.",
    directAnswer: "Most LinkedIn carousels perform best with 7 to 9 slides — enough to open with a hook, build a case across 4-6 middle slides, and close with a takeaway, without losing readers who drop off after slide 5 or 6. Shorter decks (4-5 slides) suit quick tips; longer ones (12+) risk steep swipe-through drop-off.",
    explanation: "Slide count is really a question about narrative arc, not a fixed rule. Every carousel loses a share of readers with each additional swipe — the drop-off is steepest between slides 1 and 3, where readers decide if the topic is worth their time, and it steadies out for readers who commit past that point. A 7-9 slide structure fits neatly around that curve: one hook slide, one or two slides establishing the problem, three to five slides delivering the actual value, and a closing slide with a takeaway or CTA.\n\nShorter carousels (4-5 slides) work well for a single tight idea — one framework, one before/after — where padding it out would just dilute the point. Longer carousels (12+ slides) can work for genuinely dense material, like a full step-by-step process, but they need a reason for every slide to exist; readers can tell when a deck was stretched to hit a number rather than built around content that needed the space.\n\nA common mistake is treating slide count as a vanity metric rather than a byproduct of structure — splitting one point across two slides just to hit 9, or cramming two unrelated ideas onto a single slide to keep the count low. Either move breaks the one-idea-per-slide principle that makes carousels easy to skim, and readers notice the seams even if they can't name what feels off.\n\nThe more useful test than a target number is asking whether each slide earns its place: if you could cut a slide without losing meaning, the carousel is probably longer than it needs to be. CarouseLabs' slide-flow templates default to structures in the 7-9 range for this reason, though you can extend or trim them based on how much the topic actually requires.",
    keyPoints: [
      "7-9 slides is the sweet spot for most topics — enough for a hook, substance, and a close",
      "The steepest reader drop-off happens in the first 2-3 slides, before someone commits to swiping further",
      "Short, single-idea carousels (4-5 slides) shouldn't be padded out to hit a target count",
      "Long carousels (12+ slides) only work when the material is genuinely dense enough to need the space",
    ],
    example: "An HR leader posting \"5 red flags I look for in a resume\" builds an 8-slide carousel: a hook slide, one slide per red flag (5 slides), and a closing slide inviting comments — every slide maps to a specific point, so nothing feels like filler.",
    relatedFaq: [
      { question: "Does slide count affect LinkedIn's algorithm?", answer: "Not directly — LinkedIn doesn't rank carousels by slide count. What matters is completion and dwell time, which longer, unfocused decks tend to hurt rather than help." },
      { question: "What's the minimum number of slides for a LinkedIn carousel?", answer: "There's no platform-enforced minimum, but under 4 slides usually reads better as a single image post — a carousel format implies enough content to justify swiping." },
    ],
    category: "Carousels",
    relatedSlugs: ["linkedin-carousel-dimensions", "how-long-should-a-linkedin-carousel-be", "linkedin-carousel-vs-single-image-which-performs-better", "what-is-linkedin-dwell-time"],
  },
  {
    slug: "linkedin-carousel-file-size-limit",
    question: "What is the file size limit for a LinkedIn carousel?",
    metaTitle: "LinkedIn Carousel File Size Limit Explained",
    metaDescription: "LinkedIn allows document uploads up to 100MB, but a well-built carousel PDF should land far under that. See what actually affects carousel file size.",
    directAnswer: "LinkedIn allows document uploads, including carousel PDFs, up to 100MB — a ceiling most carousels never approach, since a 10-slide PDF built well typically lands under 10MB. What actually matters is per-slide image weight: heavy, uncompressed images bloat the file and force LinkedIn's own compression to work harder, softening text after upload.",
    explanation: "The 100MB limit exists mostly as a guardrail against unusually large files, not as a number carousel creators need to plan around. A typical carousel is a handful of flat, mostly-text design slides, and those compress to a few hundred kilobytes per page in a properly exported PDF — the whole deck usually finishes well under 10MB even at 10-12 slides.\n\nWhere file size actually becomes a problem is when slides include high-resolution photos, dense gradients, or elements exported at unnecessarily high DPI. Those inflate the PDF, and LinkedIn compresses every uploaded document regardless of its size to keep the platform fast — so a bloated file just means LinkedIn's compression algorithm has to work harder on it, which is where visible quality loss creeps in: slightly blurred text edges, banding in gradients, softened photo detail.\n\nA common mistake that inflates file size unnecessarily is exporting each slide as a separate high-resolution PNG or JPEG and merging them into a PDF with a converter afterward, rather than exporting directly from the design file. That workflow often preserves every image at its original uncompressed resolution instead of the display resolution the carousel actually needs, and leftover hidden layers or unused design elements can silently ride along and add weight nobody notices until the file is oddly large.\n\nThe practical guidance is to export each slide at a reasonable resolution (1080px wide is plenty) rather than maxing out DPI settings, and to flatten complex layered designs before exporting. That keeps the file small enough that LinkedIn's compression barely touches it, so what you upload is close to what readers actually see. CarouseLabs exports carousels as an already-optimized PDF sized well under LinkedIn's limit, so file weight isn't something you need to manage by hand.",
    keyPoints: [
      "LinkedIn's document upload limit is 100MB — far more than a typical carousel PDF needs",
      "A well-exported 10-slide carousel usually lands under 10MB",
      "Heavy, high-resolution images (not slide count) are the main driver of bloated file size",
      "Smaller, well-compressed files hold up better against LinkedIn's own automatic compression on upload",
    ],
    example: "An agency owner exports a client carousel with three full-bleed, uncompressed stock photos at print-level DPI, and the PDF balloons to 45MB — after re-exporting the same design with images resized to 1080px wide, the file drops to 6MB with no visible difference in the final feed post.",
    relatedFaq: [
      { question: "Does a smaller file size improve carousel quality on LinkedIn?", answer: "Indirectly, yes — smaller, well-compressed files need less additional compression from LinkedIn on upload, which means less loss to text sharpness and image detail." },
      { question: "Can a LinkedIn carousel upload fail because of file size?", answer: "Only if it exceeds the 100MB document limit, which is rare for a standard slide deck. Failed uploads are far more often caused by file format issues than size." },
    ],
    category: "Carousels",
    relatedSlugs: ["linkedin-carousel-dimensions", "linkedin-carousel-pdf-requirements", "does-linkedin-compress-images", "how-to-make-a-linkedin-carousel-without-canva"],
  },
  {
    slug: "best-linkedin-carousel-aspect-ratio",
    question: "What is the best aspect ratio for a LinkedIn carousel?",
    metaTitle: "The Best Aspect Ratio for a LinkedIn Carousel",
    metaDescription: "The best LinkedIn carousel aspect ratios are 1:1 (square) or 4:5 (portrait) — anything taller gets letterboxed. See which ratio fits your content.",
    directAnswer: "The best aspect ratio for a LinkedIn carousel is 1:1 (square) or 4:5 (portrait, 1080×1350px) — LinkedIn's document viewer doesn't support anything taller, so a 9:16 story-style ratio gets letterboxed with wasted space. 4:5 claims more vertical feed real estate on mobile, which tends to slow the scroll and hold attention longer than square.",
    explanation: "Aspect ratio is really a question of how much of the screen your carousel controls once someone stops scrolling. A 4:5 portrait slide fills noticeably more of a phone screen than a 1:1 square slide, which means less of the next post is visible below it — that extra visual dominance is part of why portrait carousels can feel more attention-holding on mobile, where the large majority of LinkedIn's traffic happens.\n\nSquare has a different advantage: it renders predictably everywhere. LinkedIn's document viewer sometimes handles extreme ratios inconsistently across placements — the main feed, the mobile app's document preview, and any embed or notification context can each crop or letterbox slightly differently. Square's more compact frame is less likely to run into any of that, making it the safer choice when a carousel needs to look identical across every context it might appear in.\n\nWhichever ratio you pick, leave a margin of breathing room around text and key visual elements rather than running them to the very edge — slight cropping differences between preview surfaces are more forgiving when nothing important sits in the outer 5-10% of the frame. Switching ratios between posts is also worth avoiding purely for consistency: an audience that's used to seeing square carousels notices when a portrait one suddenly takes up more feed space, and that inconsistency can read as unpolished even if each individual post is well designed.\n\nNeither ratio is objectively better — the tradeoff is screen dominance versus display consistency. A visually driven carousel meant to stop the scroll on mobile often benefits from 4:5; a carousel likely to get viewed on desktop or shared outside the main feed leans safer with 1:1. What matters most is picking one ratio and using it for every slide in the deck — CarouseLabs applies a single consistent ratio across all slides automatically so a carousel never ends up with mismatched sizing mid-deck.",
    keyPoints: [
      "1:1 (square) and 4:5 (portrait) are the only ratios LinkedIn's document viewer reliably supports",
      "4:5 portrait claims more mobile screen space, which can hold attention longer than square",
      "Square renders more predictably across different feed placements and preview contexts",
      "9:16 or other tall ratios get letterboxed, wasting space rather than gaining it",
    ],
    example: "A sales rep sharing a client case study picks 4:5 portrait specifically because most of their audience views LinkedIn on mobile during commute hours, and the taller slides take up more of the screen than a square post would in the same scroll position.",
    relatedFaq: [
      { question: "Does LinkedIn support 9:16 vertical carousels?", answer: "No — the document viewer caps out around 4:5 portrait. Anything taller gets letterboxed with empty space rather than displaying edge-to-edge." },
      { question: "Should I use a different aspect ratio for desktop vs mobile viewers?", answer: "No — pick one ratio for the whole carousel. LinkedIn doesn't let you serve different versions by device, so the ratio needs to work reasonably well on both." },
    ],
    category: "Carousels",
    relatedSlugs: ["linkedin-carousel-dimensions", "linkedin-carousel-vs-single-image-which-performs-better", "best-image-size-for-linkedin-post", "how-many-slides-should-a-carousel-have"],
  },
  {
    slug: "linkedin-carousel-vs-single-image-which-performs-better",
    question: "Does a LinkedIn carousel or single image perform better?",
    metaTitle: "LinkedIn Carousel vs Single Image: Which Wins?",
    metaDescription: "Carousels generally outperform single images on LinkedIn due to longer dwell time from swiping, but single images win for simple, punchy content.",
    directAnswer: "Carousels generally outperform single images on LinkedIn because swiping keeps readers on the post longer, and that extended dwell time acts as a strong relevance signal to the algorithm. Single images still win for simple, punchy content — a bold stat, quote, or before/after shot — where a multi-slide breakdown would just slow down a message that works in one glance.",
    explanation: "The performance gap comes down to what the algorithm can measure. A single image gets viewed for a couple of seconds; a carousel that earns a full swipe-through keeps someone actively engaged with the post for much longer, and that sustained interaction is a stronger signal than a quick glance-and-scroll-past. Carousels also get a second and third chance to earn a reaction or comment, since each slide is a fresh opportunity for something to land.\n\nThe two formats also tend to earn different kinds of engagement, which matters depending on what \"performance\" means for a given post. Single images often generate faster, lower-effort reactions — quick likes on a scroll-past — while carousels that hold attention through to the last slide tend to pull more comments and saves, since a reader who finished the deck is already more invested than one who glanced at a single frame. If the goal is broad reach, either can work; if the goal is deeper engagement or being saved for later, carousels usually have the edge.\n\nThat advantage only holds if the carousel earns its length. A weak carousel — thin content stretched across slides just to create a multi-slide post — gets abandoned after slide two, and a low completion rate can undercut whatever benefit the format would have offered. A strong single image with a genuinely sharp message will usually beat a mediocre carousel; format doesn't override content quality.\n\nThe practical takeaway is to match format to the idea, not to chase the format assumed to perform best. A single striking data point or quote deserves a single image. A process, a list, a story with beats, or anything that benefits from being unpacked step by step deserves a carousel. Since carousels take real production time relative to a single image, tools like CarouseLabs that generate the full slide set from a topic in minutes make the format practical for regular posting, not just occasional flagship content.",
    keyPoints: [
      "Carousels tend to earn more dwell time because swiping is an active engagement signal, not a passive one",
      "A weak, padded-out carousel can underperform a strong single image — format doesn't override content quality",
      "Single images work best for one sharp idea: a stat, a quote, a before/after",
      "Carousels suit content with natural steps or beats — processes, lists, multi-part stories",
    ],
    example: "A product marketer tests the same feature announcement as both a single image with a headline stat and a 6-slide carousel walking through the feature's benefits — the carousel earns roughly double the comments, since each slide gives a different reason for someone to react.",
    relatedFaq: [
      { question: "Is a carousel always better than a single image for reach?", answer: "No — reach depends more on hook strength and topic relevance than format. Carousels have an engagement-time advantage, but a strong single image can still outperform a weak carousel." },
      { question: "Do carousels take longer to see results than single images?", answer: "Not in timing, but in effort — carousels generally require more production time, so the tradeoff is upfront work in exchange for a format that tends to hold attention longer once posted." },
    ],
    category: "Carousels",
    relatedSlugs: ["image-vs-text-only-linkedin-post-performance", "what-is-linkedin-dwell-time", "how-many-slides-should-a-carousel-have", "linkedin-carousel-dimensions"],
  },
  {
    slug: "linkedin-carousel-character-limit-per-slide",
    question: "What is the character limit per slide on a LinkedIn carousel?",
    metaTitle: "Character Limit Per Slide on LinkedIn Carousels",
    metaDescription: "LinkedIn sets no character limit per carousel slide — slides are images, not text fields. The real cap is legibility: roughly 20-40 words per slide.",
    directAnswer: "LinkedIn doesn't enforce a character limit per carousel slide — since slides are images inside a PDF, not a text field, there's no platform-level cap. The practical limit is legibility: keep each slide to roughly 20-40 words (about 150-200 characters) so text stays readable at the small thumbnail size carousels render at before a reader taps to expand.",
    explanation: "It helps to separate this from LinkedIn's actual character limits, like the 3,000-character caption cap — those apply to text LinkedIn's system parses and stores. A carousel slide is just pixels in a flattened image, so LinkedIn has no way to cap its text even if it wanted to; you could technically fit a full paragraph on one slide and it would upload fine.\n\nThe reason that's still a bad idea is legibility, not policy. Carousels render small in the feed before someone taps to view them full-size, and mobile screens are unforgiving of dense text at that scale. A slide with one clear headline and a short supporting line reads instantly; a slide with 80 words of body copy asks the reader to stop swiping and actually study it, which most won't do mid-scroll.\n\nA related mistake is shrinking font size to cram more words onto a slide instead of cutting the copy — this defeats the point of the length guideline entirely, since a slide can technically stay under the word count while still being unreadable at feed-preview size if the type is too small. Keeping a consistent type hierarchy across every slide (one headline size, one supporting-text size) matters as much as the word count itself, since it's what lets a reader's eye know where to look first on each new frame without pausing to figure it out.\n\nA reasonable working limit is 20-40 words per slide, split between a short headline (the point) and a line or two of support (the context). Slides that need more than that usually mean the idea should be split across two slides instead of compressed onto one. CarouseLabs generates slide copy within readable length automatically as part of each template, so text density stays consistent without needing to manually trim each slide.",
    keyPoints: [
      "There's no LinkedIn-enforced character cap on carousel slides — they're images, not text fields",
      "The real constraint is legibility at small feed-preview size, not a platform rule",
      "20-40 words per slide (roughly 150-200 characters) is a reliable readability guideline",
      "If a slide needs more text than that, split the idea across two slides instead of cramming",
    ],
    example: "A recruiter drafting a \"5 red flags in a job posting\" carousel initially writes a full explanatory paragraph on each slide, then edits every slide down to a 4-6 word headline plus one short supporting line — the deck reads in seconds instead of requiring readers to stop and study each frame.",
    relatedFaq: [
      { question: "Can a carousel slide have more text than a caption?", answer: "Technically yes, since slides aren't subject to LinkedIn's caption character limit at all — but readability, not a rule, is what keeps slide text short in practice." },
      { question: "Does font size affect how much text fits on a carousel slide?", answer: "Yes — larger, more legible fonts (recommended for mobile readability) naturally force shorter text, which is part of why well-designed carousels tend to stay concise per slide." },
    ],
    category: "Carousels",
    relatedSlugs: ["linkedin-carousel-pdf-requirements", "how-long-should-a-linkedin-carousel-be", "linkedin-caption-character-limit", "how-many-slides-should-a-carousel-have"],
  },
  {
    slug: "how-long-should-a-linkedin-carousel-be",
    question: "How long should a LinkedIn carousel be?",
    metaTitle: "How Long Should a LinkedIn Carousel Be?",
    metaDescription: "A LinkedIn carousel should take 30-45 seconds to swipe through, regardless of slide count. See how to pace word density across a deck correctly.",
    directAnswer: "A LinkedIn carousel should take a reader roughly 30-45 seconds to swipe through, regardless of exact slide count — that's the window before scroll momentum pulls someone back to their feed. Pacing matters more than length: front-load the densest information early, and taper each slide's word count as the deck moves toward a short closing takeaway.",
    explanation: "This is a different question from how many slides a carousel should have. Two carousels can both run 8 slides and read completely differently — one paced so each slide takes a second or two to absorb, another where every slide demands real reading time. Length, in the sense that actually affects performance, is total time-to-read, not a slide count.\n\nReaders build momentum as they swipe, and that momentum is fragile — a single dense, slow slide partway through a carousel is often where someone stops and exits. The fix isn't necessarily cutting content; it's controlling density. The first couple of slides can carry more information since that's where a reader is most invested in figuring out if the topic is worth their time. From there, word count per slide should generally decrease, ending in a short, low-effort closing slide (a takeaway line, a question, a CTA) that costs almost nothing to read.\n\nA common mistake that inflates perceived length without adding real value is restating the same point across two or three slides in slightly different words, usually in an attempt to stretch a thin idea to a \"respectable\" slide count. Readers register the repetition even without consciously naming it, and it reads as padding rather than depth. Visual pacing matters too — slides that rely purely on stacked text blocks feel slower to read than ones that use whitespace, a supporting image, or a large pull-quote to convey the same point with less actual reading required.\n\nThis is why two carousels with identical slide counts can have very different completion rates — one is paced to keep swipe momentum going, the other asks for the same reading effort on every slide and loses people midway through. CarouseLabs' slide templates build this taper into the structure by default, so density decreases naturally across a deck rather than staying flat from slide to slide.",
    keyPoints: [
      "Total swipe-through time (roughly 30-45 seconds) matters more than slide count for how a carousel performs",
      "Word density should taper — denser early, lighter as the deck progresses",
      "A single unusually dense slide mid-deck is a common point where readers stop swiping",
      "End on a low-effort closing slide (short takeaway or CTA) to preserve momentum to the last frame",
    ],
    example: "A financial advisor's carousel on \"how compound interest works\" opens with a slightly denser slide defining the concept, then tapers each following slide to a single example and one short line, closing on a one-line takeaway — the deck reads in under 40 seconds even though it runs 9 slides.",
    relatedFaq: [
      { question: "Is a shorter carousel always better than a longer one?", answer: "Not necessarily — a well-paced 10-slide carousel can outperform a poorly paced 5-slide one. Reading time and density matter more than raw slide count." },
      { question: "Does a longer carousel always perform worse?", answer: "No, as long as density decreases as the deck progresses. Carousels that front-load information and end on light, quick slides can run longer without losing completion rate." },
    ],
    category: "Carousels",
    relatedSlugs: ["how-many-slides-should-a-carousel-have", "linkedin-carousel-character-limit-per-slide", "what-is-linkedin-dwell-time", "best-linkedin-post-length-for-engagement"],
  },
  {
    slug: "can-you-animate-a-linkedin-carousel",
    question: "Can you animate a LinkedIn carousel?",
    metaTitle: "Can You Animate a LinkedIn Carousel?",
    metaDescription: "No — LinkedIn carousels are static PDF documents with no support for animation, GIFs, or transitions. Learn why, and what to use instead for motion.",
    directAnswer: "No — LinkedIn carousels are static PDF documents, and the platform's document viewer renders each page as a still image with no support for motion, GIFs, or video transitions. If you want movement, you'd need to post a native video instead, which uses a completely different upload and feed placement than the document/carousel format.",
    explanation: "This is a format limitation, not a design-tool limitation — no carousel creation tool, regardless of how sophisticated, can add real animation to a LinkedIn carousel, because the underlying file LinkedIn accepts for this post type is a PDF. PDFs can technically contain interactive or multimedia elements in some contexts, but LinkedIn's document viewer only renders the static page content, so any embedded motion would simply be ignored on upload.\n\nSome creators work around this by designing an animated sequence in a motion tool and exporting it as a screen-recorded video instead of a PDF. That's a legitimate way to get movement into a LinkedIn post, but it stops being a carousel at that point — it becomes a native video post, which has its own upload flow, aspect ratio rules, and feed placement, and doesn't get the swipe interaction that makes carousels distinct in the first place.\n\nThis question also comes up because other platforms blur the line — Instagram and TikTok have carousel-adjacent formats with more built-in motion options, so creators moving between platforms sometimes assume LinkedIn works the same way. It doesn't: a rapid manual swipe through well-paced static slides can feel dynamic, but that's a design and pacing effect, not actual animation, and it still requires the reader to swipe rather than watching motion play automatically.\n\nThe practical decision is choosing the right format for the content rather than trying to force motion into carousels. If the value of a post depends on movement — demonstrating a process, showing a transition — video is the right format. If the value depends on someone controlling the pace by swiping through discrete points, a static carousel is still the better fit, animation or not. CarouseLabs, like every carousel tool, produces static slides for this reason — it's a constraint of the format itself, not something a workaround fixes.",
    keyPoints: [
      "LinkedIn carousels are PDF documents, and the document viewer only renders static pages",
      "No design or carousel tool can add real animation to this format — it's a platform constraint, not a tool limitation",
      "An animated design exported as a screen-recorded video becomes a video post, not a carousel",
      "Choose video for content that depends on motion; choose a static carousel for content meant to be swiped through at the reader's pace",
    ],
    example: "An e-commerce founder wants a product demo carousel with a subtle transition effect between slides, learns LinkedIn's document viewer can't render it, and instead posts a 15-second native video for the animated walkthrough alongside a separate static carousel breaking down the product's features slide by slide.",
    relatedFaq: [
      { question: "Can you add a GIF to a LinkedIn carousel?", answer: "No — GIFs aren't supported inside a PDF document upload. LinkedIn's document viewer would render a GIF as a single static frame at best, so it wouldn't animate." },
      { question: "Does LinkedIn have a video carousel format?", answer: "No — video and carousel are separate, unrelated post types on LinkedIn. Multi-clip video sequences are not supported the way multi-slide document carousels are." },
    ],
    category: "Carousels",
    relatedSlugs: ["linkedin-carousel-pdf-requirements", "linkedin-carousel-dimensions", "linkedin-carousel-vs-single-image-which-performs-better", "can-ai-generate-linkedin-images"],
  },
  {
    slug: "linkedin-carousel-pdf-requirements",
    question: "What are the PDF requirements for a LinkedIn carousel?",
    metaTitle: "LinkedIn Carousel PDF Requirements Explained",
    metaDescription: "LinkedIn carousel PDFs need RGB color mode, consistent page size, no password protection, and embedded fonts. See the full export checklist.",
    directAnswer: "A LinkedIn carousel PDF must use RGB color mode, not CMYK, which renders dull on screens. Every page needs the same size and orientation, the file must stay under LinkedIn's 100MB limit, and it can't be password protected. Fonts should be embedded or flattened in, since an unembedded font can silently substitute to a default typeface after upload.",
    explanation: "Most of these requirements trace back to the fact that carousel PDFs were never designed for print, even though the PDF format itself was built with print in mind. Design tools sometimes default to CMYK color mode, which is calibrated for ink on paper — on a screen, CMYK colors render noticeably duller and slightly shifted compared to the same values in RGB, which is how every digital display actually renders color. Exporting in RGB from the start avoids that mismatch entirely.\n\nConsistent page size and orientation matters because LinkedIn's viewer expects a uniform document — if one page is a different size than the rest, it can scale, crop, or add unexpected margins to keep the whole file rendering as a single coherent unit. The same logic applies to font handling: if a PDF references a font by name instead of embedding or flattening it into the design, the file only displays correctly on a system that already has that font installed. LinkedIn's rendering servers don't have every custom or brand font available, so an unembedded font can quietly substitute to a generic fallback, and the carousel comes out looking noticeably different from how it was designed.\n\nPassword protection simply blocks LinkedIn's system from reading the file at all, so protected PDFs typically fail to upload outright. CarouseLabs' exports meet all of these requirements automatically — RGB color, embedded fonts, and consistent page dimensions across every slide — so there's no separate export-settings step to get right before uploading.",
    keyPoints: [
      "Export in RGB color mode, not CMYK — CMYK renders dull and shifted on screens",
      "Keep every page the same size and orientation to avoid LinkedIn scaling or cropping mismatched pages",
      "Embed or flatten fonts so custom typefaces don't silently substitute on LinkedIn's rendering servers",
      "Stay under the 100MB document limit and avoid password-protected files, which typically fail to upload",
    ],
    example: "A real estate agent exports a listing carousel from a design tool defaulted to CMYK for print, uploads it, and notices the brand's signature blue looks washed out in the feed — re-exporting the same file in RGB color mode fixes the color shift with no other changes needed.",
    relatedFaq: [
      { question: "Why do my carousel fonts look different after uploading to LinkedIn?", answer: "This usually means the fonts weren't embedded or flattened into the PDF. LinkedIn's servers substitute a default font for anything not embedded, which changes the look of the design." },
      { question: "Can I upload a PowerPoint file instead of a PDF for a carousel?", answer: "LinkedIn's document upload accepts other formats like PPT and DOCX, but PDF is the standard for carousels because it locks in exact formatting — other formats can render inconsistently depending on how LinkedIn converts them." },
    ],
    category: "Carousels",
    relatedSlugs: ["linkedin-carousel-dimensions", "linkedin-carousel-file-size-limit", "can-you-animate-a-linkedin-carousel", "how-to-make-a-linkedin-carousel-without-canva"],
  },
]
