// app/(marketing)/answers/content/hooks-writing.ts
// Hooks & Writing answer pages for the /answers/[slug] programmatic SEO system.

import type { AnswerPage } from "../types"

export const hooksWritingAnswers: AnswerPage[] = [
  {
    slug: "how-to-write-a-linkedin-hook",
    question: "How do you write a LinkedIn hook?",
    metaTitle: "How to Write a LinkedIn Hook That Stops the Scroll",
    metaDescription: "Learn how to write a LinkedIn hook using curiosity, tension, or bold claims in the first 1-2 lines — the exact copy that earns the \"see more\" click.",
    directAnswer: "Write a LinkedIn hook as the first 1-2 lines of your post that creates curiosity, states a bold claim, or highlights tension — since LinkedIn truncates posts after roughly 210 characters, your hook must work as a standalone line that earns the \"see more\" click, not as a scene-setting introduction.",
    explanation: "Most people write hooks backward — they open with context (\"Last week I was thinking about...\") and save the interesting part for line three. But LinkedIn cuts posts off after about 210 characters on desktop and even less on mobile, hiding everything past that point behind \"see more.\" If your first line is throat-clearing, most scrollers never see the actual point of your post.\n\nA working hook does one of three things: opens a curiosity gap (\"The advice everyone gives about X is backwards\"), states something specific and slightly surprising (\"I turned down a $40K contract last month\"), or names a tension your reader already feels (\"Nobody tells you this before you quit your job\"). Vague hooks (\"Let's talk about leadership\") fail because they promise nothing specific enough to earn a click.\n\nSpecificity beats cleverness. A hook with a real number, a named mistake, or a concrete outcome consistently outperforms a hook that's trying to be witty. Write your post first, then go back and mine the strongest sentence from anywhere in it — often your best hook is buried in paragraph three, not sitting where you originally opened.\n\nOne mismatch worth avoiding: a hook that promises more intensity or drama than the rest of the post delivers. A hook framed as a shocking confession followed by a mild, low-stakes observation reads as bait, and readers who feel misled by the gap are less likely to trust your next hook. The hook should set the true ceiling of the post, not exceed it.",
    keyPoints: [
      "Keep your hook inside the first ~210 characters — that's the truncation point before \"see more\" hides the rest",
      "Lead with curiosity, a bold claim, or tension, not context-setting or throat-clearing",
      "Specific details (numbers, named mistakes, concrete outcomes) outperform clever wordplay",
      "Your strongest line is often buried later in your draft — mine it and move it to the top",
      "Test multiple hook variations for the same post idea before publishing — it's the highest-leverage line you'll write",
    ],
    example: "Instead of opening with \"I've been thinking about how founders approach hiring,\" a stronger hook would be \"I rejected my best engineer's resume for a job at my own company — by accident.\" The second version names a specific, surprising event and creates an immediate question (how? why?) that only reading further can answer.",
    relatedFaq: [
      { question: "What's the character limit for a LinkedIn hook?", answer: "LinkedIn truncates posts at roughly 210 characters before showing \"see more,\" though the exact cutoff varies slightly by device. Aim to make your point or create your hook within the first 150 characters to be safe." },
      { question: "Should every LinkedIn post start with a question?", answer: "No — questions are one hook style among several, and overusing them makes your hooks predictable. Bold claims, specific numbers, and named tensions work just as well and are easier to keep varied." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["what-makes-a-good-linkedin-hook", "how-to-start-a-linkedin-post", "best-linkedin-hook-formulas", "linkedin-hook-examples-that-work"],
  },
  {
    slug: "what-makes-a-good-linkedin-hook",
    question: "What makes a good LinkedIn hook?",
    metaTitle: "What Makes a Good LinkedIn Hook? (5 Key Traits)",
    metaDescription: "A good LinkedIn hook is specific, creates curiosity, and stands alone before the \"see more\" cut. Learn the traits that separate strong hooks from weak ones.",
    directAnswer: "A good LinkedIn hook is specific, creates a genuine curiosity gap, and makes sense as a standalone line before the \"see more\" truncation. It promises something the post actually delivers, uses plain language over cleverness, and is relevant enough to your usual audience that the click leads to someone who sticks around.",
    explanation: "The traits that make a hook work are less about style and more about function — a hook's only job is to earn one more second of attention, and every quality that matters serves that job directly. Specificity matters because vague statements (\"Here's what I learned about leadership\") give the reader nothing to be curious about, while a specific one (\"I lost my best client over a single Slack message\") creates an open question that only reading further can close.\n\nRelevance is just as important as curiosity, though it gets less attention. A hook that's shocking or clickbaity but unrelated to your usual content attracts the wrong readers — people who bounce immediately, which signals low relevance back to the algorithm and can hurt distribution on the rest of the post. The strongest hooks pull in exactly the audience the post is written for.\n\nGood hooks also keep their promise. If your first line implies a dramatic story and the post delivers generic advice, readers feel the mismatch and disengage — and over time, an audience that's been burned by mismatched hooks stops trusting your first lines at all, which erodes hook effectiveness across every future post. Plain, direct language consistently outperforms hooks that reach for cleverness, since clarity is what lets the curiosity gap register instantly rather than requiring the reader to decode what you meant.\n\nA quality often overlooked is voice consistency — a hook that sounds nothing like the rest of your writing (borrowed intensity, a punchier register than you normally use) can feel manipulative even when it's technically well-constructed, because readers who've followed you for a while notice the shift. The best hooks read like an intensified version of how you already write, not a different person entirely. Testing a hook by reading it aloud is a useful check: if it sounds like something you'd actually say to a colleague, it usually clears the bar; if it sounds like ad copy, it probably needs another pass.",
    keyPoints: [
      "Specificity creates a real curiosity gap; vague statements give readers nothing to wonder about",
      "Relevance matters as much as intrigue — a hook should attract the audience the post is actually for",
      "A good hook keeps its promise; mismatched hooks and content erode reader trust over time",
      "Plain, direct language outperforms cleverness because it registers instantly",
      "A hook must stand alone as a complete thought before LinkedIn's truncation point",
    ],
    example: "A recruiter drafts two versions of the same post. The first opens with \"Hiring is changing fast in 2026\" — vague and generic. The second opens with \"I rejected a candidate for being 'overqualified.' Six months later, I regretted it.\" The second version names a specific decision and a specific consequence, giving readers an actual reason to keep reading.",
    relatedFaq: [
      { question: "Does a good hook need to be surprising?", answer: "Not necessarily — a hook can also work by naming a tension the reader already feels or making a clear, specific claim. Surprise is one path to curiosity, not the only one." },
      { question: "Can a hook be too clever?", answer: "Yes. If a reader has to pause and decode what a hook means, it's failed its job. Clarity should always come before wordplay, since confusion kills momentum before curiosity can build." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "best-linkedin-hook-formulas", "why-is-my-linkedin-hook-not-working", "linkedin-hook-examples-that-work"],
  },
  {
    slug: "how-to-start-a-linkedin-post",
    question: "How should you start a LinkedIn post?",
    metaTitle: "How to Start a LinkedIn Post (Without Losing Readers)",
    metaDescription: "Start a LinkedIn post with a specific, self-contained line — not context or setup. See what to avoid and how to open a post that earns the click.",
    directAnswer: "Start a LinkedIn post with a specific, self-contained statement — a claim, a result, or a moment of tension — rather than context-setting or a greeting. The opening line has to work on its own before LinkedIn truncates the post, so it needs to make a point immediately instead of building up to one.",
    explanation: "Most weak openers share the same structural problem: they spend the first line setting a scene instead of making a point. Something like \"So last week I had an interesting conversation with a client\" is a perfectly normal way to start telling a story out loud, but on LinkedIn it wastes the one line that's guaranteed to be seen by everyone who scrolls past. The reader has no reason to expand the post yet, because nothing has actually been said.\n\nThe fix is to open with the outcome or the tension, then backfill the setup afterward. Instead of leading into the client conversation, open with what happened as a result of it: \"A client fired us the same week we hit their best quarter ever.\" That line is specific, creates an immediate question, and doesn't need any prior context to make sense.\n\nGreetings, disclaimers, and throat-clearing (\"Excited to share...\", \"I don't usually post about this, but...\") fall into the same trap — they delay the actual content and often signal to an experienced LinkedIn reader that a generic post is coming, which invites them to keep scrolling rather than stop. Writing the body of the post first and then extracting its strongest, most specific line as the opener is a more reliable process than trying to write a great opening line cold.\n\nA related mistake is opening with the conclusion instead of the tension that leads to it — stating \"Delegation is the key to scaling a team\" upfront gives away the lesson before the reader has any reason to care how you arrived at it. Opening with the moment before the lesson was learned, rather than the lesson itself, preserves the reason to keep reading. It also helps to read your opening line completely isolated from the rest of the post — if it doesn't hold up as an interesting sentence on its own, it isn't ready to lead.",
    keyPoints: [
      "Open with a claim, result, or moment of tension — not scene-setting or a greeting",
      "The first line must make sense with zero prior context",
      "Avoid throat-clearing phrases like \"Excited to share\" or \"I don't usually post about this\"",
      "Write the post body first, then pull your strongest specific line to use as the opener",
    ],
    example: "An HR leader drafts a post starting with \"I wanted to share some thoughts on employee retention this quarter.\" Rewritten, it opens with \"We lost three senior employees in one month — and it wasn't about salary.\" The rewrite states a specific, surprising fact instead of announcing that thoughts are coming.",
    relatedFaq: [
      { question: "Is it okay to start a LinkedIn post with a question?", answer: "It can work, but it's easy to overuse. A specific claim or result usually creates stronger curiosity than a generic question like \"Ever wonder why...\", which readers have seen too many times to react to." },
      { question: "Should I start a LinkedIn post with an emoji?", answer: "Leading with an emoji instead of words wastes visual space that could carry an actual hook. A well-placed emoji later in the post works better than one used as an opener." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "first-line-linkedin-post-character-limit", "how-to-write-attention-grabbing-linkedin-post", "best-linkedin-caption-structure"],
  },
  {
    slug: "best-linkedin-hook-formulas",
    question: "What are the best LinkedIn hook formulas?",
    metaTitle: "5 Best LinkedIn Hook Formulas (With Examples)",
    metaDescription: "The best LinkedIn hook formulas include the failure-to-lesson, contrarian-claim, and numbered-promise structures. See how each one works with examples.",
    directAnswer: "The strongest LinkedIn hook formulas are the failure-to-lesson hook (naming a specific mistake before the takeaway), the contrarian-claim hook (challenging common advice), the numbered-promise hook (\"3 things I'd do differently\"), and the before-and-after hook (contrasting a past and current state). Each works by creating a distinct type of curiosity gap.",
    explanation: "Hook formulas are useful because they give you a repeatable structure instead of requiring a fresh flash of creativity for every post. The failure-to-lesson formula (\"I turned down a $50K deal — here's why it was the right call\") works because admitting a specific mistake or unusual decision signals honesty, which readers are drawn to more than polished success stories.\n\nThe contrarian-claim formula (\"Networking events are a waste of time for most people\") works by pushing against something the reader already believes, creating tension that can only be resolved by reading the reasoning that follows. It only works if the claim is defensible — a contrarian hook that can't be backed up in the post reads as bait rather than insight.\n\nThe numbered-promise formula (\"4 hiring mistakes I made in my first year as a manager\") works differently — it sets a concrete expectation for value and length, which lowers the reader's risk in clicking \"see more\" because they know roughly what they're getting into. The before-and-after formula (\"My pipeline was empty in January. By March, it was full.\") compresses a transformation into one line, letting the body of the post explain how.\n\nNo formula works if it's applied to a post that doesn't deliver on the specific promise made in the opening line — the formula creates the gap, but the post still has to close it.\n\nA fifth pattern worth knowing is the direct-address formula (\"If you're a manager reading this before your first layoff conversation, stop scrolling\"), which works by naming the exact reader instead of a general topic — it trades broad reach for sharper relevance, since the people it's not written for skip past it quickly while the intended reader feels directly spoken to. Formulas are also easy to overuse in combination; stacking a numbered promise on top of a contrarian claim in the same line often reads as try-hard rather than compelling. Picking one mechanic per hook keeps the line clean.",
    keyPoints: [
      "Failure-to-lesson: name a specific mistake or unusual decision before the takeaway",
      "Contrarian claim: challenge common advice, but only if the post can defend the claim",
      "Numbered promise: set a concrete expectation (\"3 things...\") that lowers the reader's risk in clicking through",
      "Before-and-after: compress a transformation into a single line, then explain the how",
      "Every formula fails if the post doesn't deliver on the specific promise the hook made",
    ],
    example: "A sales rep uses the before-and-after formula: \"Six months ago I was closing 1 deal a month. Last month I closed 9.\" The post then breaks down the specific process change that caused the jump, fulfilling the promise the hook set up rather than leaving it vague.",
    relatedFaq: [
      { question: "Should I reuse the same hook formula every time?", answer: "No — repeating one formula post after post makes your openings predictable, which readers pick up on quickly. Rotating between two or three formulas keeps your hooks feeling fresh." },
      { question: "Is the contrarian hook formula risky?", answer: "It can be, if the claim is exaggerated purely for attention. It works best when you genuinely hold the position and can back it up, not as a manufactured controversy." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "linkedin-hook-examples-that-work", "how-to-write-a-curiosity-hook", "what-makes-a-good-linkedin-hook"],
  },
  {
    slug: "how-to-write-a-hook-that-stops-scrolling",
    question: "How do you write a hook that stops the scroll on LinkedIn?",
    metaTitle: "How to Write a LinkedIn Hook That Stops the Scroll",
    metaDescription: "Stop the scroll on LinkedIn with a hook that interrupts a pattern — a specific claim, number, or tension readers can't skim past. See how to write one.",
    directAnswer: "A hook stops the scroll by interrupting the pattern readers expect from a feed of generic professional updates — using a specific number, an unexpected claim, or a visible moment of tension that can't be processed and dismissed in a glance. Predictable openers get filtered out by the reader's brain before they're consciously read; unusual ones don't.",
    explanation: "Scrolling through LinkedIn is largely a pattern-matching activity — readers aren't reading every word, they're skimming for signals that a post is worth stopping for, and most posts fail that skim test instantly because they open with familiar shapes: an announcement, a thank-you, a generic observation. A hook stops the scroll by breaking that expected shape, forcing a half-second of actual reading instead of a skim.\n\nSpecific numbers are one of the most reliable interrupters, because round or vague claims blend into the background while an oddly specific one stands out: \"we lost 14 customers in a single week\" reads differently than \"we lost a lot of customers.\" The specificity itself signals that this is a real account, not a generic observation, which is often the actual trigger for stopping.\n\nVisible tension works the same way — a hook that implies conflict, risk, or an unresolved outcome (\"My co-founder and I almost didn't survive our first year\") can't be resolved by skimming past it, because the reader's brain registers an open loop. Formatting plays a supporting role too: a short punchy first line followed by a line break reads faster than a dense opening sentence, and reading speed at the very top of a post affects whether a scroller's eye catches it at all before the thumb keeps moving.\n\nContext also matters — what stops a scroll depends partly on what's surrounding it in the feed that day. A calm, understated hook can stand out precisely because everything nearby is loud, while an aggressive hook can blend into a feed already full of similar intensity. There's no universal maximum intensity that works every time, which is why testing a few hook styles over several weeks and watching which ones actually produce early comments is more reliable than assuming any single technique will always win the scroll.",
    keyPoints: [
      "Predictable openers (announcements, thank-yous, generic observations) get filtered out during skimming",
      "Specific, slightly odd numbers interrupt the pattern better than round or vague ones",
      "Visible tension or an unresolved outcome creates an open loop the reader's brain wants closed",
      "Short first lines with a line break after them are easier to catch mid-scroll than dense sentences",
    ],
    example: "An agency owner rewrites \"We had a great quarter\" as \"We fired our biggest client and grew revenue anyway.\" The second version names a specific, tension-loaded event that a scrolling thumb is more likely to pause on than a generic positive statement.",
    relatedFaq: [
      { question: "Does formatting affect whether a hook stops the scroll?", answer: "Yes — a short first line followed by a line break is easier to register at a glance than a long, dense opening sentence, even if the wording is equally strong." },
      { question: "Can a scroll-stopping hook feel like clickbait?", answer: "It can, if the tension it implies isn't real or isn't resolved in the post. The goal is genuine specificity, not exaggeration — readers who feel baited disengage from future posts too." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "how-to-write-attention-grabbing-linkedin-post", "what-makes-a-good-linkedin-hook", "why-is-my-linkedin-hook-not-working"],
  },
  {
    slug: "first-line-linkedin-post-character-limit",
    question: "What is the character limit for the first line of a LinkedIn post?",
    metaTitle: "LinkedIn First-Line Character Limit (2026)",
    metaDescription: "LinkedIn truncates posts at roughly 210 characters before showing \"see more.\" Aim to make your hook's point within the first 140–150 characters to be safe.",
    directAnswer: "LinkedIn truncates posts at approximately 210 characters on desktop before showing \"see more,\" though mobile often cuts off earlier, around 140 characters depending on screen size. To be safe across devices, aim to make your hook's core point within the first 140–150 characters rather than relying on the full desktop limit.",
    explanation: "The truncation point isn't a fixed, published number — LinkedIn doesn't document an exact character count, and the cutoff varies slightly by device, font rendering, and whether the post includes line breaks, since each line break consumes vertical space that counts toward when \"see more\" appears. This is why the widely cited figure of roughly 210 characters should be treated as an approximation, not a precise rule to write against.\n\nMobile is the tighter constraint in practice, since the majority of LinkedIn traffic happens on phones and mobile screens show noticeably less text before truncating than desktop does. A hook that fits neatly within 210 characters on desktop can still get cut off mid-sentence on a phone, which is why writers who account only for the desktop number often end up with awkward truncation points in the wild.\n\nLine breaks compound this — a post that uses a line break after the first sentence effectively \"spends\" more of its visible character budget on that one line, since LinkedIn counts vertical space, not just character count, when deciding where to insert \"see more.\" A short, punchy first line followed by a line break can actually get less visible text on mobile than a longer first line with no break at all. The safest approach is writing the hook to fully land within roughly 140 characters, then treating anything beyond that as a bonus rather than something you're relying on being seen.",
    keyPoints: [
      "Desktop truncation happens around 210 characters, but this is an approximation, not a documented rule",
      "Mobile cuts off earlier than desktop, often around 140 characters, and carries most LinkedIn traffic",
      "Line breaks consume vertical space and can trigger truncation earlier than the raw character count suggests",
      "Write your hook to fully land within roughly 140 characters to be safe across devices",
    ],
    example: "A consultant writes a hook that reads perfectly on desktop at 200 characters, but checks it on their phone and finds it cuts off mid-sentence at \"I spent three years building a process that...\" — an incomplete thought that doesn't earn a click. They shorten the hook to under 140 characters so it lands as a complete statement on both devices.",
    relatedFaq: [
      { question: "Does LinkedIn ever change the truncation point?", answer: "The exact cutoff has shifted before as LinkedIn updates its app and web layouts, which is another reason to write hooks with margin rather than targeting the limit precisely." },
      { question: "Do line breaks always hurt visibility before the truncation point?", answer: "Not always — a short, high-impact first line can still be worth a line break for readability. The tradeoff is fewer characters visible before \"see more,\" which is only a problem if the hook needed those extra characters to land." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "how-to-start-a-linkedin-post", "how-long-should-a-linkedin-post-be", "how-to-add-line-breaks-in-linkedin-post"],
  },
  {
    slug: "how-to-write-attention-grabbing-linkedin-post",
    question: "How do you write an attention-grabbing LinkedIn post?",
    metaTitle: "How to Write an Attention-Grabbing LinkedIn Post",
    metaDescription: "Write an attention-grabbing LinkedIn post with a specific hook, tight formatting, and a payoff that matches the promise. See the full structure that works.",
    directAnswer: "An attention-grabbing LinkedIn post combines a specific, curiosity-driven hook with tight formatting (short lines, white space) and a body that pays off exactly what the hook promised. Attention isn't only about the opening line — a strong hook followed by a bloated or generic body loses readers just as fast as a weak hook does.",
    explanation: "Attention-grabbing is often treated as a hook-only problem, but it's really a full-post problem with three stages: earning the click, keeping the read, and rewarding it. The hook's job is narrow — get the \"see more\" click — but if the paragraph right after the hook doesn't immediately continue the thread the hook opened, readers bail within the first few lines regardless of how strong the opener was.\n\nFormatting does real work here. Long, dense paragraphs are harder to enter mid-scroll than short lines separated by white space, because the reader's eye needs an easy on-ramp — a wall of text signals effort required, and most scrollers aren't willing to invest that effort before they're hooked. Breaking the body into short, scannable chunks keeps the visual momentum from the hook going.\n\nThe payoff matters more than either of those individually. A post can have a great hook and clean formatting and still underperform if the ending doesn't deliver value proportional to what the opening promised — readers remember posts that under-deliver, and that memory quietly reduces how much they trust your future hooks. The strongest attention-grabbing posts treat the hook as a contract: whatever tension or curiosity it opens, the rest of the post is structured specifically to close it, not to wander into a loosely related point.\n\nThe ending deserves as much attention as the hook, since it's what determines whether someone comments, which is the signal that extends reach the most. A post that grabs attention but ends flatly — trailing off without a clear takeaway or prompt — leaves engagement on the table even after doing the hard part of earning the read. Closing with a specific, answerable question tied to the post's actual content, rather than a generic \"thoughts?\", converts attention that's already been earned into visible engagement instead of a silent read.",
    keyPoints: [
      "Attention-grabbing is a full-post structure, not just a strong opening line",
      "The paragraph after the hook must immediately continue the thread the hook opened",
      "Short lines and white space make a post easier to enter mid-scroll than dense paragraphs",
      "The payoff has to match the hook's promise, or readers lose trust in your future hooks",
    ],
    example: "A startup founder opens with \"We almost ran out of runway three months before our best quarter ever.\" The post then breaks the recovery into three short, specific decisions rather than a vague reflection on \"resilience,\" so the ending delivers the concrete payoff the hook implied.",
    relatedFaq: [
      { question: "Is formatting really that important for attention?", answer: "Yes — dense paragraphs create a visible barrier to entry on a fast-scrolling feed, even when the underlying writing is strong. Short lines with white space lower that barrier." },
      { question: "Can a post be too short to grab attention?", answer: "A post can be short and still work if it fully delivers its point — length isn't the issue, mismatch between the hook's promise and the body's payoff is." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "how-to-write-a-hook-that-stops-scrolling", "best-linkedin-caption-structure", "how-to-add-line-breaks-in-linkedin-post"],
  },
  {
    slug: "linkedin-hook-examples-that-work",
    question: "What are examples of LinkedIn hooks that work?",
    metaTitle: "10 LinkedIn Hook Examples That Actually Work",
    metaDescription: "See real LinkedIn hook examples that work, across formats like the failure hook, contrarian claim, and numbered promise, with why each one succeeds.",
    directAnswer: "Working LinkedIn hooks share a specific claim or moment readers can't skim past: \"I turned down $40K to keep my agency small,\" \"Nobody warns you that your first hire is the hardest one,\" or \"3 interview questions that told me more than any resume.\" Each succeeds by being concrete, creating an open question, and matching what the rest of the post actually delivers.",
    explanation: "Looking at working hooks side by side shows the pattern more clearly than any single rule. \"I turned down $40K to keep my agency small\" works because it states an unusual, counterintuitive decision with a specific number attached — the reader immediately wants to know why anyone would do that. \"Nobody warns you that your first hire is the hardest one\" works differently, by naming a shared, relatable pain point that experienced readers recognize instantly and newer readers want to understand before they hit it themselves.\n\n\"3 interview questions that told me more than any resume\" works through the numbered-promise structure — it sets a concrete expectation of exactly what's coming, which lowers the reader's risk in clicking through because the payoff is clearly scoped. A hook like \"My biggest mistake as a manager cost us our best employee\" works through the failure-to-lesson pattern, trading polish for honesty in a way that consistently earns trust.\n\nWhat these examples have in common isn't tone or topic — one is confident, one is empathetic, one is instructional — it's that each is specific enough to be un-skimmable and each is answered, not just implied, in the body of the post that follows. A hook copied verbatim from a list won't work if the post behind it doesn't deliver the same specificity; the example only works because a real, concrete story or lesson backs it up.",
    keyPoints: [
      "Working hooks state something specific and unusual, not a generic topic announcement",
      "Different hook types (contrarian decision, shared pain point, numbered promise, failure-to-lesson) all work through the same core mechanic: an open question the body answers",
      "Numbered hooks succeed by scoping the payoff, which lowers the reader's risk in clicking through",
      "A hook only works if the post behind it delivers real specificity — copying the phrasing without the substance falls flat",
    ],
    example: "A freelance designer uses \"I fired my highest-paying client last month\" as a hook. It works because it's specific, counterintuitive, and immediately answerable — the post that follows explains the client relationship's actual cost, delivering exactly what the hook implied rather than a generic post about setting boundaries.",
    relatedFaq: [
      { question: "Can I reuse a hook example directly on my own post?", answer: "The phrasing pattern can be adapted, but the specific details need to be genuinely yours — a copied hook with generic or fabricated details reads as hollow and won't hold up once readers click through." },
      { question: "Do question-based hooks work as well as statement hooks?", answer: "Statement hooks with specific claims generally outperform question hooks, since questions are easy to skim past without mentally engaging, while a specific claim demands a reaction." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "best-linkedin-hook-formulas", "what-makes-a-good-linkedin-hook", "how-to-write-a-curiosity-hook"],
  },
  {
    slug: "why-is-my-linkedin-hook-not-working",
    question: "Why is my LinkedIn hook not working?",
    metaTitle: "Why Your LinkedIn Hook Isn't Working (Common Fixes)",
    metaDescription: "A LinkedIn hook often fails because it's too vague, buried in setup, or over-promises what the post delivers. See the 4 most common causes and fixes.",
    directAnswer: "A LinkedIn hook usually fails for one of four reasons: it's too vague to create real curiosity, the actual point is buried after a line of context, it promises something the rest of the post doesn't deliver, or it sounds like every other hook in the feed. Diagnosing which one applies is more useful than rewriting blindly.",
    explanation: "Vagueness is the most common failure. A hook like \"Here's something I've been thinking about lately\" technically opens the post but gives the reader nothing concrete to be curious about — there's no specific claim, number, or event to react to, so the brain has no reason to stop scrolling. The fix is almost always to find the most specific sentence in the post and move it to the top.\n\nBuried hooks are the second failure mode: the actual interesting line exists in the post, but it's sitting in paragraph two or three after a sentence of setup (\"Last week I was talking to a client and something they said really stuck with me...\"). By the time the interesting part arrives, the post has already been truncated or scrolled past. Reordering — leading with the interesting line and filling in context afterward — usually fixes this without changing a word of the actual content.\n\nOver-promising is subtler and shows up in engagement data rather than the hook itself: a strong hook gets clicks, but comments and shares stay low because the body doesn't deliver what the opening implied, so readers feel let down and don't engage further. Finally, formulaic overuse — leading with \"Unpopular opinion:\" or \"Nobody talks about this, but...\" on every post — trains an audience to recognize and discount the pattern itself, regardless of what follows. Rotating hook styles and grounding each one in a genuinely specific detail addresses all four causes at once.",
    keyPoints: [
      "Vague hooks give readers nothing specific to be curious about — find the most concrete line in your post and lead with it",
      "Buried hooks hide the interesting line behind a sentence of setup; reordering usually fixes this without new content",
      "Over-promising hooks get clicks but low comments/shares because the body doesn't match the opening's implication",
      "Formulaic openers (\"Unpopular opinion:\", \"Nobody talks about this...\") lose effectiveness once an audience recognizes the pattern",
    ],
    example: "A career coach notices their posts get clicks but few comments. Reviewing the last ten posts, every hook uses \"Unpopular opinion:\" as an opener — the audience has started skimming past the phrase itself. Switching to hooks built from specific client situations instead of the recycled phrase restores engagement within a few posts.",
    relatedFaq: [
      { question: "How do I know which failure mode applies to my hook?", answer: "Check engagement patterns: low click-through suggests vagueness or a buried hook, while decent clicks but weak comments suggest the body isn't delivering on the hook's promise." },
      { question: "Can a hook fail even if it follows a proven formula?", answer: "Yes — a formula only provides structure. If the specific detail plugged into it is generic or the post doesn't back up the claim, the formula alone won't rescue it." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "what-makes-a-good-linkedin-hook", "best-linkedin-hook-formulas", "how-to-write-a-hook-that-stops-scrolling"],
  },
  {
    slug: "how-to-write-a-curiosity-hook",
    question: "How do you write a curiosity hook for LinkedIn?",
    metaTitle: "How to Write a Curiosity Hook for LinkedIn",
    metaDescription: "Write a curiosity hook for LinkedIn by opening a specific, unresolved question the post answers — without giving away the resolution in the first line.",
    directAnswer: "Write a curiosity hook by opening a specific, unresolved question in the first line — naming a surprising outcome, an odd decision, or a withheld detail — without revealing the resolution until later in the post. The gap between what's implied and what's explained is what pulls the reader past the truncation point.",
    explanation: "A curiosity gap works on a simple psychological mechanic: an incomplete pattern is harder to ignore than a complete one. A hook like \"We changed one thing in our onboarding process and cut churn by a third\" is effective specifically because it withholds the one thing — naming it upfront would close the gap immediately and remove the reason to keep reading. The skill in curiosity hooks is deciding exactly what to reveal and what to hold back.\n\nThe most common mistake is holding back too little or too much. Revealing too much collapses the gap in the hook itself, leaving nothing for the post to resolve. Holding back too much — being cryptic about even the general subject — makes the hook feel like clickbait with no substance behind it, since the reader can't tell if the eventual payoff is even relevant to them. The balance point is naming the category of the outcome (churn, a hire, a client) while withholding the specific mechanism or number that explains it.\n\nCuriosity hooks also need a believable stakes signal — the outcome has to matter enough that the reader wants the answer. \"I changed my morning routine\" opens a weak gap because the stakes are low; \"I changed one habit and it saved my business\" opens a stronger one because the implied consequence is significant. The post that follows has to resolve the gap clearly, not just gesture at it, or the curiosity mechanic backfires into reader frustration.\n\nTiming the reveal inside the post also matters. Resolving the gap too early, in the second line, wastes the curiosity you just built and makes the rest of the post feel like an afterthought; delaying it too long past the truncation point risks losing readers who wanted the answer but weren't willing to keep clicking through unrelated setup. Placing the resolution roughly a third of the way into the post, after just enough context to make it land, tends to hold readers through to the end rather than losing them at either extreme.",
    keyPoints: [
      "Name the category of the outcome, but withhold the specific mechanism or number until later in the post",
      "Revealing too much in the hook closes the curiosity gap before the post can use it",
      "Being too cryptic makes a hook feel like unsubstantiated clickbait",
      "Higher implied stakes create a stronger curiosity gap than low-stakes, minor details",
    ],
    example: "A B2B marketer writes \"We stopped doing something every marketing guide recommends — and our lead quality doubled.\" The hook names the category (a common marketing practice) and the outcome (doubled lead quality) without revealing what was cut, and the post resolves it by naming the specific tactic and explaining why dropping it worked.",
    relatedFaq: [
      { question: "How much should a curiosity hook reveal?", answer: "Enough to signal what category the payoff belongs to (a process, a decision, a number) without giving away the specific detail that resolves it — that detail is what earns the click." },
      { question: "Can a curiosity hook backfire?", answer: "Yes, if the post doesn't clearly resolve the gap it opened. A curiosity hook that trails off into a vague or unrelated point leaves readers feeling misled, which discourages them from clicking on future hooks." },
    ],
    category: "Hooks & Writing",
    relatedSlugs: ["how-to-write-a-linkedin-hook", "best-linkedin-hook-formulas", "linkedin-hook-examples-that-work", "what-makes-a-good-linkedin-hook"],
  },
]
