// app/(marketing)/answers/content/images-visuals.ts
// Images & Visuals answer pages for the /answers/[slug] programmatic SEO system.

import type { AnswerPage } from "../types"

export const imagesVisualsAnswers: AnswerPage[] = [
  {
    slug: "best-image-size-for-linkedin-post",
    question: "What is the best image size for a LinkedIn post?",
    metaTitle: "Best Image Size for a LinkedIn Post (2026)",
    metaDescription: "The best LinkedIn image size is 1200×1500px (4:5) or 1200×1200px (square) for feed posts. See the exact pixel dimensions and aspect ratios to use.",
    directAnswer: "The best image size for a single LinkedIn feed post is 1200×1500px (4:5 portrait) or 1200×1200px (1:1 square). Portrait uses more vertical space in the mobile feed and tends to hold attention longer while scrolling, while square displays reliably across both desktop and mobile without any cropping risk.",
    explanation: "LinkedIn's feed doesn't enforce a single fixed image size the way some platforms do — it accepts a range of dimensions and crops or letterboxes anything outside its preferred ratios. That's why picking a size isn't really about finding the one \"correct\" number, it's about picking a ratio LinkedIn's feed handles predictably rather than one it has to guess how to crop.\n\n1200×1500px (4:5) has become the practical default for creators optimizing for engagement because it's the tallest ratio LinkedIn will display in-feed without adding letterboxing or forcing a crop, and taller images occupy more of the screen on mobile, where the majority of LinkedIn traffic happens. That extra screen real estate tends to slow the scroll down for a fraction of a second longer, which is often enough to earn a stop instead of a scroll-past.\n\n1200×1200px (square) is the safer choice when you're less certain how an image will be viewed, since it displays consistently on both desktop and mobile without any risk of the top or bottom being clipped in a preview. Wider landscape images (16:9 or similar) are the weakest choice for feed posts — they take up the least vertical space on mobile and are the easiest to scroll past. Whichever ratio you pick, export at these pixel dimensions directly rather than resizing a smaller image up, since upscaling introduces visible softness that LinkedIn's own compression will make worse.\n\nA common mistake is designing text or logos right to the edge of the frame — feed and share previews sometimes trim a small margin, so keep key elements at least 60-80px inside the border on every side. CarouseLabs applies these dimensions automatically when generating a post image, so the sizing decision doesn't require manual setup.",
    keyPoints: [
      "1200×1500px (4:5 portrait) maximizes mobile screen space and scroll-stopping power",
      "1200×1200px (square) is the safest default across desktop and mobile viewing",
      "Landscape (16:9) images take up the least feed space and are easiest to scroll past",
      "Export at full target resolution — don't upscale a smaller image to fit",
    ],
    example: "A career coach who previously posted 1600×900px landscape screenshots switches to 1200×1500px portrait graphics for the same quote-card content; with identical captions and posting times, the portrait versions hold a visibly larger footprint in the mobile feed and start pulling more profile clicks per post.",
    relatedFaq: [
      { question: "Is portrait or square better for a LinkedIn image post?", answer: "Portrait (4:5) generally wins on mobile attention because it takes up more vertical scroll space, but square is the more foolproof choice if you're posting the same image across multiple platforms with different crop behavior." },
      { question: "What happens if my image doesn't match LinkedIn's preferred ratio?", answer: "LinkedIn will crop or letterbox it to fit the feed's display area, which can cut off text or important visual elements near the edges — always design with a safe margin inside the frame." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["linkedin-single-image-dimensions", "does-linkedin-compress-images", "how-to-make-a-linkedin-post-image", "linkedin-carousel-dimensions"],
  },
  {
    slug: "linkedin-single-image-dimensions",
    question: "What are the correct dimensions for a single LinkedIn image post?",
    metaTitle: "LinkedIn Single Image Post Dimensions (2026)",
    metaDescription: "Correct LinkedIn single-image dimensions: 1200×1500px (4:5) or 1200×1200px (1:1), under 5MB, in JPG or PNG. Full spec and file-size guidance inside.",
    directAnswer: "A single LinkedIn image post should be 1200×1500px (4:5 portrait) or 1200×1200px (1:1 square), saved as a JPG or PNG under LinkedIn's 5MB upload limit. Aim for a file size in the 500KB–2MB range at those dimensions — large enough to stay sharp, small enough that LinkedIn's automatic compression doesn't degrade it further.",
    explanation: "Dimensions and file size are two separate constraints that both affect how sharp an image looks once it's live, and treating them as one setting is where most posts go wrong. The pixel dimensions (1200×1500 or 1200×1200) determine how much detail is available before any compression happens. The file size determines how much of that detail survives LinkedIn's upload pipeline, which re-compresses every image to keep its platform fast — a bloated, uncompressed export at the right dimensions can still come out blurry if LinkedIn has to compress it aggressively to bring it under its own internal thresholds.\n\nThe practical target is exporting at the correct pixel dimensions using a moderate JPG compression setting (roughly 80-85% quality) yourself, before upload. This produces a file typically in the 500KB-2MB range that's already efficiently compressed, so LinkedIn's own compression pass has little extra work to do and the visible quality loss is minimal. Uploading a 10-15MB uncompressed PNG at the same dimensions doesn't get you a sharper result — it just shifts more of the compression work onto LinkedIn's servers, where you have no control over the settings.\n\nPNG is worth using specifically for images with flat colors, text, or logos, where its lossless compression avoids the slight blur JPG can introduce around sharp edges. Photographic images compress more efficiently as JPG without a visible quality difference.\n\nAnother common mistake is exporting in an Adobe RGB or CMYK profile carried over from print design software — LinkedIn expects standard sRGB, and a different profile can leave colors looking washed out or shifted once uploaded, even though the file looks correct on your own screen. CarouseLabs generates images at the correct dimensions and sRGB color profile automatically, so that's one less setting to get wrong.",
    keyPoints: [
      "1200×1500px (4:5) or 1200×1200px (1:1) are the two reliable dimension choices",
      "Stay under LinkedIn's 5MB upload cap, ideally targeting 500KB–2MB",
      "Pre-compress at 80-85% JPG quality so LinkedIn's own compression has less to do",
      "Use PNG for text/logo-heavy graphics, JPG for photographic content",
    ],
    example: "A UX designer uploading a 14MB uncompressed PNG portfolio graphic notices visible artifacting around the text after LinkedIn processes it; re-exporting the same file at 1200×1500px with 85% JPG compression drops it to 900KB, and the compressed-on-upload version now looks noticeably cleaner than the original oversized file did.",
    relatedFaq: [
      { question: "What is LinkedIn's maximum file size for image posts?", answer: "LinkedIn caps single-image uploads at 5MB. Files near that limit typically get compressed hard by LinkedIn's own pipeline, so pre-compressing to under 2MB usually preserves more visible quality." },
      { question: "Does image resolution matter if LinkedIn compresses everything anyway?", answer: "Yes — compression reduces file size, not the underlying pixel dimensions. Starting from a properly sized, sharp source image always compresses better than starting from a low-resolution or blurry one." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["best-image-size-for-linkedin-post", "does-linkedin-compress-images", "linkedin-image-format-requirements", "linkedin-carousel-dimensions"],
  },
  {
    slug: "does-linkedin-compress-images",
    question: "Does LinkedIn compress images?",
    metaTitle: "Does LinkedIn Compress Images? What Happens on Upload",
    metaDescription: "Yes, LinkedIn compresses every uploaded image to reduce file size and speed up feed loading. Learn how to minimize visible quality loss from that process.",
    directAnswer: "Yes, LinkedIn automatically compresses every image uploaded to a post, regardless of its original quality or file size. This happens to keep the feed loading quickly across devices and connection speeds. You can't disable it, but exporting at the right dimensions with moderate pre-compression minimizes how much visible quality LinkedIn's pass strips away.",
    explanation: "Every major social platform re-encodes uploaded media to control server load and feed loading speed, and LinkedIn is no exception. The compression is applied uniformly regardless of how carefully the original file was prepared, which is why two images that look identical before upload can look noticeably different afterward — the one that was already efficiently compressed loses very little in a second compression pass, while the one uploaded as a huge, uncompressed file gets compressed much more aggressively to hit LinkedIn's internal size targets.\n\nThe visible symptoms of over-compression are usually banding in gradients, softened text edges, and blocky artifacts around high-contrast boundaries — exactly the areas where carousel slides and quote graphics tend to concentrate detail. Flat-color graphics with sharp text are more vulnerable to visible degradation than photographs, because compression artifacts are more obvious against clean edges and solid color fields than they are in the natural noise of a photo.\n\nThe mitigation isn't avoiding compression — that's not possible — it's controlling how much work LinkedIn's compression has to do. A file that's already been exported at the correct pixel dimensions with sensible JPG compression arrives close to its final, efficient state, so LinkedIn's pass makes minimal additional changes. A raw, oversized export forces LinkedIn to do most of the compression itself, with much less predictable results than doing it yourself beforehand.\n\nCompression also isn't static — LinkedIn has adjusted its pipeline multiple times to optimize feed loading speed, so a pre-compression workflow that worked well a year ago may need periodic retesting. The most reliable check is simply viewing your own post live on a phone after publishing, since that's the only way to see exactly what your actual audience sees, rather than trusting how the file looks in your design tool before upload.",
    keyPoints: [
      "LinkedIn compresses all uploaded images automatically — this cannot be turned off",
      "Compression artifacts show up most visibly in gradients, text edges, and flat color fields",
      "Pre-compressing your own export minimizes how much additional compression LinkedIn applies",
      "Photographic images tend to hide compression artifacts better than flat-color graphics or text",
    ],
    example: "A speaker uploads the same quote graphic twice — once as an uncompressed 12MB PNG and once as a pre-compressed 800KB JPG at identical pixel dimensions — and the pre-compressed version renders visibly crisper in the feed, while the uncompressed original shows soft, blurred text edges after LinkedIn's processing.",
    relatedFaq: [
      { question: "Can I stop LinkedIn from compressing my images?", answer: "No, compression is applied automatically to every uploaded image and can't be disabled. The only control you have is how efficiently the file is compressed before you upload it." },
      { question: "Why do my carousel slides look blurrier after posting than they did in my design tool?", answer: "This is almost always LinkedIn's compression pass interacting badly with an oversized or under-compressed export. Re-exporting at the correct target dimensions with moderate JPG compression usually resolves it." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["linkedin-single-image-dimensions", "linkedin-image-format-requirements", "linkedin-carousel-file-size-limit", "best-image-size-for-linkedin-post"],
  },
  {
    slug: "linkedin-image-format-requirements",
    question: "What are LinkedIn's image format requirements?",
    metaTitle: "LinkedIn Image Format Requirements (2026)",
    metaDescription: "LinkedIn accepts JPG, PNG, and GIF for image posts, up to 5MB. JPG suits photos, PNG suits text and logos, GIF supports simple animation.",
    directAnswer: "LinkedIn accepts JPG, PNG, and GIF file formats for image posts, with a maximum file size of 5MB per image. JPG is best for photographs, PNG is best for graphics with text, logos, or flat colors where sharp edges matter, and GIF is the only format that supports animation, though it's rarely used for standard feed image posts.",
    explanation: "Format choice affects two things that matter for how a post ultimately looks: how the file compresses and whether it supports transparency or motion. JPG uses lossy compression tuned for photographic detail — it handles natural color gradients and complex textures efficiently at small file sizes, which is why it's the default for camera photos and photo-based graphics. Its weakness is sharp edges and flat color fields, where lossy compression can introduce visible softness or artifacting, which matters more for design-heavy content like carousel slides or quote cards than it does for a photo.\n\nPNG uses lossless compression, which preserves sharp text edges and flat colors perfectly but produces larger files for the same visual complexity — a reasonable tradeoff for a slide with clean typography and a solid background, a poor one for a detailed photograph, where PNG files balloon in size without a visible quality benefit over JPG.\n\nGIF is technically supported but limited to a much smaller color palette than JPG or PNG, which makes it a poor choice for anything beyond simple animated graphics — it's rarely the right choice for standard post images. LinkedIn does not accept formats like WEBP, TIFF, or BMP for direct image uploads, so files in those formats need to be converted to JPG or PNG before posting. Regardless of format, every upload is still capped at 5MB and subject to LinkedIn's own compression pass on top of whatever compression the source file already has.\n\nTransparency is another format-specific consideration: PNG supports a transparent background, but LinkedIn renders posts on a white card in light mode and a dark card in dark mode, so a logo with transparency and dark text can look fine for half your audience and nearly invisible for the other half. Testing any transparent PNG against both a light and dark backdrop before posting catches this early.",
    keyPoints: [
      "LinkedIn image posts accept JPG, PNG, and GIF only — not WEBP, TIFF, or BMP",
      "JPG suits photographs; PNG suits text-heavy graphics, logos, and flat-color designs",
      "GIF supports animation but its limited color palette makes it a poor fit for most post images",
      "All formats share the same 5MB file size cap regardless of which one you choose",
    ],
    example: "A brand designer tries uploading a WEBP export of a client logo graphic and the upload fails silently in the composer; converting the same file to PNG at identical dimensions resolves the issue immediately and also preserves the logo's transparent background, which the JPG alternative would have flattened to white.",
    relatedFaq: [
      { question: "Does LinkedIn support WEBP images?", answer: "No, LinkedIn's post composer does not accept WEBP uploads for standard image posts. Convert WEBP files to JPG or PNG before uploading." },
      { question: "Can I post an animated GIF as a LinkedIn image post?", answer: "Yes, GIF is a supported format and will play back animated, though its limited color depth makes it unsuitable for detailed photography or design work." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["does-linkedin-compress-images", "linkedin-single-image-dimensions", "linkedin-carousel-pdf-requirements", "best-image-size-for-linkedin-post"],
  },
  {
    slug: "should-every-linkedin-post-have-an-image",
    question: "Should every LinkedIn post have an image?",
    metaTitle: "Should Every LinkedIn Post Have an Image? (2026)",
    metaDescription: "No, not every LinkedIn post needs an image. Text-only posts can outperform visuals for strong personal stories, while visuals help data and how-to content.",
    directAnswer: "No, not every LinkedIn post needs an image. Text-only posts with a strong hook and a compelling personal story or opinion often perform just as well, sometimes better, than image posts, because the text itself is the entire value of that format. Images earn their place when they add information or visual interest text can't — data, before/after comparisons, quotes, or step-by-step breakdowns.",
    explanation: "The instinct that every post needs a visual comes from platforms where images are structurally required or heavily favored, but LinkedIn's feed doesn't systematically favor image posts over text posts — it favors whatever earns strong early engagement, and a text post's hook can do that job on its own. A well-written personal story or contrarian opinion often benefits from having nothing between the reader and the words; adding an unnecessary graphic on top of a post that's already carried by its writing can actually dilute focus rather than add to it.\n\nWhere images genuinely help is when the content has a visual component the text can't fully replace: a chart showing a real trend, a screenshot of an actual result, a before/after comparison, or a multi-step framework that's easier to scan as a graphic than to read as a paragraph. In those cases the image isn't decoration, it's carrying real information load.\n\nThe practical filter is asking whether the image adds something the text alone can't communicate. If the answer is no — if it's a generic stock photo or an unrelated headshot tacked on out of habit — it's likely neutral at best for engagement and can even distract from a strong hook. If the answer is yes, the image is doing real work and belongs there. Treating \"add an image\" as a default checklist item rather than a case-by-case decision produces a feed full of posts where the visual and the text are fighting for the same attention instead of reinforcing each other.",
    keyPoints: [
      "LinkedIn's algorithm doesn't systematically favor image posts over well-written text posts",
      "Strong personal stories and opinions often work better as pure text, letting the hook carry the post",
      "Images earn their place when they convey information text can't — data, screenshots, comparisons, frameworks",
      "A generic or unrelated image can dilute a strong text hook rather than support it",
    ],
    example: "A startup founder posts a raw, text-only account of a failed product launch that generates strong comment volume purely from the story; the following week they add a stock photo of a laptop to a similar post out of habit, and it underperforms the text-only version despite covering a comparable topic.",
    relatedFaq: [
      { question: "Do LinkedIn posts without images get less reach?", answer: "Not inherently. LinkedIn's algorithm weighs engagement signals like comments and dwell time far more heavily than whether a post includes media, so a strong text-only post can outperform a weak image post." },
      { question: "What kind of content benefits most from an image?", answer: "Content with a genuine visual component — data, screenshots, step-by-step frameworks, before/after comparisons — benefits most, since the image adds information the text alone can't convey as efficiently." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["image-vs-text-only-linkedin-post-performance", "how-to-make-a-linkedin-post-image", "what-increases-linkedin-reach", "should-i-post-personal-stories-on-linkedin"],
  },
  {
    slug: "image-vs-text-only-linkedin-post-performance",
    question: "Do image posts or text-only posts perform better on LinkedIn?",
    metaTitle: "Image vs. Text-Only LinkedIn Posts: Which Performs Better?",
    metaDescription: "Neither format wins outright on LinkedIn — text-only posts often win on comments for strong stories, while images win on dwell time for data-heavy content.",
    directAnswer: "Neither format consistently outperforms the other on LinkedIn — performance depends on how well the format matches the content. Text-only posts tend to win on comment volume when the writing itself is the value (stories, opinions, lessons). Image posts tend to win on dwell time and visual engagement when they carry information a paragraph can't compress as well, like data or frameworks.",
    explanation: "The \"which performs better\" framing assumes format is the primary variable, but content-format fit matters more than format alone. A compelling personal story loses very little by being pure text, since the entire mechanism that drives engagement — the reader relating to or reacting to the narrative — lives entirely in the words. Adding an image to that kind of post doesn't add a second engagement driver; it just sits alongside the real one.\n\nImage posts pull ahead specifically when the visual is doing work a paragraph of text would do less efficiently: a chart makes a trend immediately legible in a way describing the same trend in prose can't match, and a well-designed framework graphic can be scanned in seconds versus read in a minute. That efficiency shows up as dwell time, which LinkedIn's algorithm weighs meaningfully — people who spend longer looking at a post send a stronger relevance signal than people who scroll past quickly, even without commenting.\n\nCarousels sit in an interesting middle position worth noting separately: because they require an active swipe rather than a passive glance, they tend to generate even higher dwell time than a single static image, which is part of why carousels are often the top performer of the three formats for content that has enough substance to spread across multiple slides. The practical takeaway isn't \"pick images\" or \"pick text\" as a blanket rule — it's matching the format to whether the content's value lives in the writing or in something visual the writing can't replace.",
    keyPoints: [
      "Text-only posts tend to win on comments when the writing itself carries the value",
      "Image posts tend to win on dwell time when the visual conveys information more efficiently than prose",
      "Dwell time is a meaningful algorithmic signal independent of comments or reactions",
      "Carousels often outperform both single images and text for substantial, multi-part content, since swiping increases dwell time further",
    ],
    example: "A data analyst posts the same insight two ways in back-to-back weeks — once as a text-only paragraph describing a metric shift, once as a simple line-chart graphic showing the same data — the chart version holds noticeably longer average view time, while the text version actually pulls in more comments because it reads as a personal take rather than just a data point.",
    relatedFaq: [
      { question: "Does adding an image always increase LinkedIn engagement?", answer: "No — an image only helps when it adds real value beyond the text. A relevant chart or screenshot can boost dwell time, but a generic decorative image often makes no measurable difference." },
      { question: "Is dwell time more important than comments for LinkedIn reach?", answer: "Both matter, but they're not interchangeable. Comments signal strong reaction and often trigger wider redistribution, while dwell time signals sustained relevance — the strongest posts tend to earn both." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["should-every-linkedin-post-have-an-image", "what-is-linkedin-dwell-time", "linkedin-carousel-vs-single-image-which-performs-better", "what-increases-linkedin-reach"],
  },
  {
    slug: "how-to-make-a-linkedin-post-image",
    question: "How do you make a LinkedIn post image?",
    metaTitle: "How to Make a LinkedIn Post Image (2026 Guide)",
    metaDescription: "Make a LinkedIn post image with a design tool like Canva, a designer, or CarouseLabs, which generates a matching post image directly from your topic.",
    directAnswer: "You can make a LinkedIn post image with a design tool like Canva, by hiring a designer, or with CarouseLabs, which generates a fully designed post image directly from a topic in the correct dimensions automatically, with no manual design work required. Design skill matters less than picking an approach you can sustain consistently.",
    explanation: "There are a few legitimate paths to a usable LinkedIn post image, and the right one depends mostly on how much time and design skill you have available, not on which single method is \"correct.\" Canva and similar drag-and-drop tools give the most creative control but require picking fonts, colors, and layout yourself each time, which is fine for someone who enjoys design but becomes a real time cost for someone posting several times a week. Hiring a designer produces the most polished, brand-consistent output but is slow and expensive to do for every individual post, so it tends to suit templated batches rather than one-off images. A stock photo with a simple text overlay is the fastest manual option but is also the easiest to spot as generic, and generic imagery does little to make a post stand out in a feed.\n\nCarouseLabs takes a different approach: instead of starting from a blank canvas, you describe the topic or idea you want to post about, and it generates a complete post image — layout, typography, and color already applied consistently — sized correctly for LinkedIn's feed. This removes the design-tool step entirely rather than making it faster, which matters most for people posting regularly who don't want image creation to be the bottleneck on how often they publish.\n\nNone of these approaches is universally best. A brand with strict visual guidelines may still prefer a designer or a locked-down Canva template. Someone testing content ideas quickly benefits more from a fast, low-friction option like CarouseLabs or a simple text-overlay image than from investing design time into every post before knowing which topics resonate.",
    keyPoints: [
      "Canva and similar tools offer full creative control but cost real time per post",
      "A designer produces the most polished result but doesn't scale to frequent, one-off posting",
      "Stock photo plus text overlay is fast but often reads as generic in a crowded feed",
      "CarouseLabs generates a ready-to-post image directly from a topic, skipping manual design entirely",
    ],
    example: "A solo consultant who used to spend 20-30 minutes in Canva building each quote graphic switches to describing the same idea to CarouseLabs instead, gets a finished, correctly sized post image in under a minute, and starts posting visual content twice as often simply because the design step stopped being the bottleneck.",
    relatedFaq: [
      { question: "Do I need design skills to make a good LinkedIn post image?", answer: "Not necessarily. Template-based tools like Canva reduce the design skill required, and AI tools like CarouseLabs remove the manual design step entirely by generating a finished image from a written topic." },
      { question: "What's the fastest way to make a LinkedIn post image?", answer: "Generating one directly from a topic description, as CarouseLabs does, is typically the fastest path since it skips choosing fonts, colors, and layout by hand — a text-overlay-on-stock-photo approach is the fastest fully manual option." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["how-to-make-a-linkedin-carousel-without-canva", "best-image-size-for-linkedin-post", "should-every-linkedin-post-have-an-image", "best-ai-tool-for-linkedin-content"],
  },
  {
    slug: "linkedin-infographic-size-guide",
    question: "What size should a LinkedIn infographic be?",
    metaTitle: "LinkedIn Infographic Size Guide (2026)",
    metaDescription: "LinkedIn infographics should be built at 1200×1500px (4:5) for feed posts, or split across a 1080×1350px carousel when the content needs more space.",
    directAnswer: "A LinkedIn infographic for a single feed image should be built at 1200×1500px (4:5 portrait), the tallest ratio the feed displays without cropping. If the infographic has more content than a single portrait frame can hold legibly, split it across a carousel at 1080×1350px per slide instead of shrinking everything to fit one image.",
    explanation: "Infographics are the image type most likely to fail from being sized wrong, because they usually pack in more text, data points, and visual hierarchy than a quote card or a photo does. At 1200×1500px, small text and detailed charts are still legible on a phone screen if the layout keeps a clear hierarchy — a headline, a small number of clearly separated sections, and enough white space that nothing feels cramped. Push much more content into that same single frame and text sizes drop to the point where they're unreadable at typical mobile viewing size, no matter how correct the pixel dimensions are.\n\nThis is the actual decision point for infographic sizing: it's not really about finding a bigger canvas, since LinkedIn's feed won't display a meaningfully larger single image than 1200×1500px in a useful way, but about whether the content fits at readable text sizes within that frame at all. When it doesn't, splitting the same information across a carousel — each slide at 1080×1350px, covering one section of the infographic per slide — solves the problem properly instead of fighting it. This also plays to LinkedIn's format strengths, since carousels tend to hold attention longer than a single dense image because the swipe interaction itself demands active engagement.\n\nA good rule of thumb: if an infographic needs more than roughly 4-5 distinct data points or sections to make its point, it's very likely a carousel candidate rather than a single-image candidate, regardless of how technically correct its dimensions are.",
    keyPoints: [
      "1200×1500px (4:5 portrait) is the ideal single-image infographic size for LinkedIn's feed",
      "Legibility at mobile viewing size matters more than fitting everything into one frame",
      "Infographics with more than roughly 4-5 sections usually work better as a carousel",
      "Carousel slides for split infographic content should use 1080×1350px per slide",
    ],
    example: "A supply-chain consultant tries to cram a 7-step process into one 1200×1500px infographic and the text becomes unreadable on mobile; splitting the same 7 steps across a 7-slide carousel at 1080×1350px each keeps every step legible and the post ends up with a noticeably higher completion rate through the swipes.",
    relatedFaq: [
      { question: "Should a LinkedIn infographic be one image or a carousel?", answer: "It depends on content density. A simple infographic with a few clear sections works as one image; anything with several distinct data points or steps usually reads better split across a carousel." },
      { question: "What's the minimum text size for a readable LinkedIn infographic?", answer: "There's no universal number since it depends on the design, but as a practical check, view your export at actual phone screen size before posting — if body text is straining to read there, it's too small or the frame has too much content." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["best-image-size-for-linkedin-post", "linkedin-carousel-dimensions", "how-many-slides-should-a-carousel-have", "how-to-make-a-linkedin-post-image"],
  },
  {
    slug: "best-colors-for-linkedin-post-images",
    question: "What are the best colors for LinkedIn post images?",
    metaTitle: "Best Colors for LinkedIn Post Images (2026)",
    metaDescription: "The best LinkedIn image colors are high-contrast, consistent with your brand palette, and distinct from LinkedIn's own blue-and-white UI to stand out in feed.",
    directAnswer: "The best colors for a LinkedIn post image are a small, high-contrast palette (2-3 core colors) that's visually distinct from LinkedIn's own blue-and-white interface, so the image reads clearly and stands out against the feed rather than blending into it. Strong text-to-background contrast matters more than any specific color choice, since most viewing happens on small mobile screens.",
    explanation: "Color choice on LinkedIn interacts with a constraint that's easy to overlook: the platform's own interface is heavily blue and white, so an image using a similar pale blue palette can visually recede into the surrounding UI instead of standing out as content. This isn't about avoiding blue entirely — plenty of strong brands use blue deliberately — it's about making sure the specific shade and contrast level of your image creates a clear boundary against the feed around it, rather than blurring into it.\n\nContrast matters more than any specific hue. Dark text on a light background or light text on a dark, saturated background both work reliably; low-contrast combinations like gray text on a light gray background, or pastel-on-pastel palettes, look elegant on a large monitor but frequently become hard to read at the small size and often-imperfect brightness of a phone screen, where most LinkedIn viewing happens. A useful gut check is squinting at the design or shrinking it to thumbnail size — if the text or key element is still clearly legible, the contrast is doing its job.\n\nBeyond legibility, consistency compounds over time. Reusing the same 2-3 core colors across every post image builds a visual signature that makes your content recognizable in the feed before someone even reads the headline, which is a meaningful advantage for anyone posting regularly. Constantly changing palettes forfeits that recognition even if each individual image looks fine on its own.\n\nDark mode adds another wrinkle worth checking: LinkedIn's interface switches between light and dark backgrounds depending on the viewer's device settings, and a palette designed only against white can lose contrast when the surrounding UI shifts to dark. Previewing a design against both backdrops before finalizing a palette avoids a color scheme that only works for part of your audience.",
    keyPoints: [
      "Use a small, consistent palette of 2-3 core colors across your post images",
      "Prioritize strong text-to-background contrast over any specific color trend",
      "Avoid pale blue-and-white palettes that can blend into LinkedIn's own interface",
      "A consistent color palette builds recognizability in the feed over time",
    ],
    example: "A fintech founder whose post images used a light blue-on-white palette nearly identical to LinkedIn's own UI switches to a dark navy background with a single warm accent color for headlines; the new images are visibly easier to spot while scrolling, and the founder keeps that exact palette across every subsequent post to build recognition.",
    relatedFaq: [
      { question: "Should I match my LinkedIn post image colors to my brand colors?", answer: "Yes, ideally — brand-consistent colors build recognition over time, as long as the specific shades used still maintain strong contrast and don't visually disappear into LinkedIn's blue-and-white interface." },
      { question: "Do bright colors get more engagement on LinkedIn?", answer: "Not inherently. High contrast and legibility drive engagement more reliably than brightness alone — a well-contrasted dark palette can stand out just as effectively as a bright one." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["how-to-make-a-linkedin-post-image", "linkedin-infographic-size-guide", "should-every-linkedin-post-have-an-image", "linkedin-carousel-dimensions"],
  },
  {
    slug: "how-many-images-can-you-post-on-linkedin",
    question: "How many images can you post on LinkedIn?",
    metaTitle: "How Many Images Can You Post on LinkedIn? (2026)",
    metaDescription: "LinkedIn allows up to 9 images in a single multi-image post, or up to 20 slides in a carousel document. Here's when to use each format.",
    directAnswer: "LinkedIn allows up to 9 images in a single multi-image post, displayed as a swipeable gallery. Separately, carousels (uploaded as PDF documents) support up to 20 slides. A standard single-image post is just one image; the multi-image and carousel formats are distinct upload options within the composer, not extensions of the same limit.",
    explanation: "It's worth separating LinkedIn's two multi-image options because they behave differently and serve different purposes, and conflating them leads to picking the wrong format. A multi-image post is a quick gallery of up to 9 separate photos or graphics, swiped through the same way a carousel is, but each image is independent — there's no enforced reading order, no consistent template requirement, and no PDF export step. It's well suited to a set of standalone photos, like event shots or product angles, where each image stands on its own.\n\nA carousel is structurally different: it's a single PDF document, uploaded as one file, where slides are explicitly designed to be read in sequence and typically share a consistent visual template. This is the format built for step-by-step frameworks, story arcs, or any content where slide order matters and each slide builds on the last. The 20-slide cap gives meaningfully more room than the 9-image cap, but more slides isn't automatically better — most well-performing carousels land in a much tighter 6-10 slide range, since completion rate drops the longer the swipe sequence runs.\n\nThe practical decision: if the images are independent and order doesn't matter, use the multi-image gallery. If the content tells a sequential story or walks through steps where order and visual consistency matter, use a carousel instead, and treat the 20-slide ceiling as a hard limit to design within rather than a target to hit.\n\nA common mistake is uploading a sequential, step-by-step graphic as a multi-image post because it's faster to prepare, only to have viewers swipe through the images out of the intended order since a multi-image gallery has no enforced sequence the way a carousel's fixed PDF page order does. Save the multi-image format for genuinely standalone visuals, and use a carousel whenever order matters.",
    keyPoints: [
      "Multi-image posts support up to 9 independent images in a swipeable gallery",
      "Carousels (PDF uploads) support up to 20 slides, designed to be read in sequence",
      "Multi-image galleries suit standalone content; carousels suit sequential, templated content",
      "Most high-performing carousels use far fewer than 20 slides, typically in the 6-10 range",
    ],
    example: "An event photographer uploads 9 photos from a conference as a multi-image gallery post since each photo stands alone, while the same week posts an 8-slide carousel walking through a networking framework, using the carousel format specifically because that content needs to be read start to finish in order.",
    relatedFaq: [
      { question: "Is a multi-image post the same as a carousel on LinkedIn?", answer: "No — a multi-image post is a gallery of up to 9 independent images with no required order, while a carousel is a single PDF document of up to 20 slides designed to be read sequentially." },
      { question: "What's the best number of images for a multi-image LinkedIn post?", answer: "There's no fixed ideal, but 3-6 well-chosen images tend to hold attention better than maxing out at 9, since a gallery that's too long risks the same drop-off in completion that overly long carousels see." },
    ],
    category: "Images & Visuals",
    relatedSlugs: ["how-many-slides-should-a-carousel-have", "linkedin-carousel-file-size-limit", "linkedin-carousel-vs-single-image-which-performs-better", "linkedin-carousel-pdf-requirements"],
  },
]
